#version 150

#moj_import <fog.glsl>

// The shipped surface atlas (bubbleshield:textures/effect/surface_atlas.png,
// bound by ShieldPipelines' per-effect RenderType through its
// TextureStateShard): an 8x4 grid of 32 seamless grayscale tiles. Per texel:
// R = coarse structure, G = mid detail, B = fine grain, A = EMISSION mask
// (glow, NOT transparency). All hue comes from vertexColor at runtime
// (recolor-safe).
uniform sampler2D Sampler0;
// Vanilla auto-filled uniforms (declared in fx_NNN.json; ShaderInstance
// .setDefaultUniforms fills them every draw). GameTime spans one day cycle
// in [0, 1); FogShape picks the vanilla fog metric (0 = spherical).
uniform float GameTime;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;
uniform int FogShape;

// Bubble surface shader fx_117 -- family RINGS
// stack: deep=caustic x3 taps | mid=rings+none+pulse | rim=graze_sparkle | flourish=shimmer | tex=starfield | motif=corex1+breath
// fbm: ridged x3 octaves | seed 8c8b6d777864054e
// v12 realism (1.21.1): glass tint 0.3126+Beer 0.6062*chord | energy 0.2351+0.4461*p | flow 0.051667 c/s | floor 0.3896
// GENERATED by tools/gen_surface_shaders.py -- do not hand-edit; edit the
// generator and regenerate instead (byte-stable, fixed seed).

in vec2 texCoord0;
in vec4 vertexColor;
in float sphericalVertexDistance;
in float cylindricalVertexDistance;
// Camera-relative world-space position from surface.vsh: the camera is
// the origin of this space, so view direction = -normalize(worldPos).
in vec3 worldPos;

out vec4 fragColor;

// 1 - smoothstep with ASCENDING edges. Replaces every reversed-edge
// smoothstep(hi, lo, x) call: edge0 >= edge1 is undefined by the GLSL
// spec; this form is numerically identical on conforming drivers.
float invsmooth(float lo, float hi, float x) {
    return 1.0 - smoothstep(lo, hi, x);
}

// Rodrigues rotation matrix around a baked unit axis. Driven with an
// angle that completes an INTEGER number of turns per day, the daily
// time wrap 1200 -> 0 lands exactly on a full turn -- the catalogue's
// first true (non-shear) rotation animation, only legal on the 3D
// sphere-direction domain (a 2D UV rotation would break the u wrap).
mat3 rotA(vec3 axis, float a) {
    float s = sin(a);
    float c = cos(a);
    float oc = 1.0 - c;
    return mat3(
        oc * axis.x * axis.x + c, oc * axis.x * axis.y + axis.z * s, oc * axis.z * axis.x - axis.y * s,
        oc * axis.x * axis.y - axis.z * s, oc * axis.y * axis.y + c, oc * axis.y * axis.z + axis.x * s,
        oc * axis.z * axis.x + axis.y * s, oc * axis.y * axis.z - axis.x * s, oc * axis.z * axis.z + c);
}

float hash21(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

vec2 hash22(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * vec3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.xx + p3.yz) * p3.zy);
}

// Hoskins-style 3D->1D hash; small multiplier keeps fp32 precision
// alive over the whole sphere-direction domain
float hash31(vec3 p3) {
    p3 = fract(p3 * 0.1031);
    p3 += dot(p3, p3.zyx + 31.32);
    return fract((p3.x + p3.y) * p3.z);
}

// lattice-cell hash that tiles across the longitude seam: the cell's
// x id wraps every px cells, so u = 0 and u = 1 sample identical cells
float cellHash(vec2 cellId, float px) {
    return hash21(vec2(mod(cellId.x, px), cellId.y));
}

// value noise on a wrapping lattice (quintic fade): 'per' tiles the
// field so it is seamless across the u = 0/1 longitude wrap
float vnoise(vec2 p, vec2 per) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float a = hash21(mod(i, per));
    float b = hash21(mod(i + vec2(1.0, 0.0), per));
    float cc = hash21(mod(i + vec2(0.0, 1.0), per));
    float d = hash21(mod(i + vec2(1.0, 1.0), per));
    return mix(mix(a, b, u.x), mix(cc, d, u.x), u.y);
}

// 3D value noise (quintic fade). Sampled on the sphere direction the
// domain is periodic across the u seam AND uniform at the poles by
// construction, so unlike the 2D lattice it needs NO wrap period.
float vnoise3(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    vec3 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float n000 = hash31(i);
    float n100 = hash31(i + vec3(1.0, 0.0, 0.0));
    float n010 = hash31(i + vec3(0.0, 1.0, 0.0));
    float n110 = hash31(i + vec3(1.0, 1.0, 0.0));
    float n001 = hash31(i + vec3(0.0, 0.0, 1.0));
    float n101 = hash31(i + vec3(1.0, 0.0, 1.0));
    float n011 = hash31(i + vec3(0.0, 1.0, 1.0));
    float n111 = hash31(i + vec3(1.0, 1.0, 1.0));
    return mix(mix(mix(n000, n100, u.x), mix(n010, n110, u.x), u.y),
        mix(mix(n001, n101, u.x), mix(n011, n111, u.x), u.y), u.z);
}

// fractal noise, ridged mode, 3 octaves. The x lacunarity
// is exactly 2 and the lattice period doubles with it, so EVERY octave
// tiles the longitude seam (a rotation here would break the wrap).
float fbm2(vec2 p, vec2 per) {
    float value = 0.0;
    float amplitude = 0.5;
    for (int i = 0; i < 3; i++) {
        value += amplitude * (1.0 - abs(2.0 * vnoise(p, per) - 1.0));
        p = vec2(p.x * 2.0, p.y * 2.1924) + vec2(17.7, 9.2);
        per = vec2(per.x * 2.0, per.y * 2.1924);
        amplitude *= 0.5;
    }
    return value;
}

// jaybird-style iterated caustic: noise-displaced resampling + exp
// sharpen. The wrapping lattice keeps it seamless across the u seam;
// the caller passes a day-quantized drift.
float caustic(vec2 p, vec2 drift, vec2 per) {
    vec2 k = p;
    float acc = 0.0;
    for (int i = 0; i < 3; i++) {
        float fi = float(i);
        float w = vnoise(k + drift + vec2(fi * 3.7, fi * 1.3), per);
        k += 0.35 * vec2(cos(w * 6.2831853), sin(w * 6.2831853));
        acc += w;
    }
    acc = acc / 3.0;
    return clamp(exp(acc * 3.0 - 1.9) - 0.35, 0.0, 1.4);
}

// iterated caustic on the 3D sphere direction: noise-displaced
// resampling + exp sharpen, seam- and pole-free by construction.
// Motion comes from the caller rotating the domain (day-safe).
float caustic3(vec3 p, float t) {
    vec3 k = p;
    float acc = 0.0;
    for (int i = 0; i < 3; i++) {
        float fi = float(i);
        float w = vnoise3(k + vec3(fi * 3.7, fi * 1.3, fi * 2.1));
        k += 0.35 * vec3(cos(w * 6.2831853), sin(w * 6.2831853), cos(w * 4.1887902 + 1.7));
        acc += w;
    }
    acc = acc / 3.0;
    return clamp(exp(acc * 3.0 - 1.9) - 0.35, 0.0, 1.4);
}

// iq cosine palette, baked per effect; used ONLY for bounded accents
vec3 accentPalette(float t) {
    return vec3(0.5) + vec3(0.5) * cos(6.2831853 * (vec3(0.4161, 0.9258, 0.5409) * t
        + vec3(0.2586, 0.4933, 0.4692)));
}

// 3-stop shadow/body/highlight grade (two smoothstep segments): every
// stop is derived from vertexColor.rgb at RUNTIME, so the owner /color
// override recolors shadow, body and highlight together (recolor-safe
// by construction).
vec3 gradient3(vec3 deepStop, vec3 body, vec3 hotStop, float x) {
    vec3 g = mix(deepStop, body, smoothstep(0.0, 0.4888, x));
    return mix(g, hotStop, smoothstep(0.4888, 1.0, x));
}

// saturation lift: mixes AWAY from luma (s > 1), deepening the chroma
// without changing the hue -- the anti-washout pass
vec3 satLift(vec3 col, float s) {
    float l = dot(col, vec3(0.299, 0.587, 0.114));
    return clamp(mix(vec3(l), col, s), 0.0, 1.0);
}

// Rodrigues rotation of the color vector around the grey axis; nudges
// the highlight stop's hue away from the body color. The input is
// always derived from vertexColor.rgb at runtime, so recolor-safe.
vec3 hueSpin(vec3 col, float a) {
    const vec3 k = vec3(0.57735027);
    float ca = cos(a);
    float sa = sin(a);
    return col * ca + cross(k, col) * sa + k * dot(k, col) * (1.0 - ca);
}

// silhouette estimator: the camera-distance varying changes fastest per
// pixel at grazing angles, so fwidth() peaks at the bubble's rim.
// Normalizing by the distance itself keeps the rim width roughly
// view-consistent near and far.
float rimGraze() {
    float g = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    return smoothstep(0.0030, 0.0550, g);
}

// hash-cell twinkle: sparse offset star points with per-cell phase;
// cells wrap every px in x so the field tiles the u seam
float sparkle(vec2 p, float t, float px) {
    vec2 cellId = floor(p);
    vec2 f = fract(p) - 0.5;
    float h = cellHash(cellId, px);
    vec2 off = vec2(cellHash(cellId + 11.3, px), cellHash(cellId + 27.9, px)) - 0.5;
    float d = length(f - off * 0.55);
    float tw = pow(0.5 + 0.5 * sin(t * (2.0 + 5.0 * h) + h * 39.0), 6.0);
    return step(0.7012, h) * invsmooth(0.02, 0.22, d) * tw;
}

// GameTime-phased expanding rings from hash-seeded surface points; the
// chordal x-distance (sin of the longitude difference) keeps the rings
// round across the u = 0/1 seam, and the phase speed is day-quantized
float ringPulse(vec2 uv, float t) {
    float acc = 0.0;
    for (int i = 0; i < 3; i++) {
        float fi = float(i);
        vec2 c = hash22(vec2(fi * 7.31 + 9.1760, fi * 2.97));
        float phase = fract(t * 0.120000 + fi * 0.37);
        float d = length(vec2(sin((uv.x - c.x) * 3.1415927) * 0.3183, uv.y - c.y));
        acc += invsmooth(0.0, 0.05, abs(d - phase * 0.7)) * (1.0 - phase);
    }
    return acc;
}

// one inset-clamped tap of this file's surface-atlas tile: fract()
// wraps the (seam-periodic) repeat domain, and the inset keeps the
// linear-filtered lookup inside the tile for ANY flow/gradient offset
// (8x4 tile grid -> per-axis scale vec2(0.125, 0.25))
vec4 atlasTile(vec2 p) {
    return texture(Sampler0, (vec2(0.0000, 1.0000) + clamp(fract(p), 0.004, 0.996)) * vec2(0.125, 0.25));
}

// DEEP-layer field (3D refracted caustic volume), sampled on the 3D sphere direction by
// the correlated parallax planes -- seam- and pole-free
float deepField(vec3 p, float t) {
    return caustic3(p, t);
}

void main() {
    // GameTime spans one day cycle in [0, 1); scale to roughly seconds.
    // All constant speeds below are day-quantized (integer cycles or
    // integer lattice periods per day) so the daily wrap does not pop.
    float time = GameTime * 1200.0;
    // texCoord0 is the raw sphere UV, already in [0,1]; fract() is only a
    // defensive wrap. Seam-freedom in u comes from the wrapping-lattice /
    // periodic-domain sampling below, NOT from this fract().
    vec2 baseUV = fract(texCoord0);
    vec2 midPer = vec2(3.0000, 5.0000);
    // 3D sphere direction reconstructed from the UV (u -> longitude,
    // v -> latitude): any field sampled on it is periodic across the
    // u = 0/1 seam AND uniform at the poles by construction.
    vec3 sdir = vec3(sin(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        cos(3.1415927 * baseUV.y),
        sin(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    // v11: the view direction is hoisted up here (the thickness and
    // parallax layers need it before the normal block) together with
    // its component TANGENT to the shell surface: Vt is the true
    // parallax direction -- zero head-on, maximal at the grazing limb,
    // seam-safe by construction (pure 3D geometry, no UV involved).
    vec3 viewV = -normalize(worldPos);
    vec3 Vt = viewV - dot(viewV, sdir) * sdir;

    // [palette:gradient3]
    // Runtime 3-stop palette derived from vertexColor.rgb: the dark stop
    // darkens AND saturates (base*base stays in-hue instead of greying);
    // the hot stop is a LUMA-CAPPED CHROMATIC highlight -- a hue-nudged,
    // saturation-lifted, brightened base whose luma is capped relative to
    // the base luma, so the highlight can NEVER wash out toward white.
    // The owner /color override replaces vertexColor wholesale, so the
    // whole ramp re-derives from it -- recolor-safe by construction.
    vec3 baseCol = vertexColor.rgb;
    vec3 deepStop = baseCol * baseCol * 0.6633;
    vec3 spun = clamp(hueSpin(baseCol, -0.4747), 0.0, 1.0);
    vec3 hotStop = satLift(spun, 1.1003) * 1.45;
    float hotLuma = dot(hotStop, vec3(0.299, 0.587, 0.114));
    float lumaCap = max(0.4792, dot(baseCol, vec3(0.299, 0.587, 0.114)) * 1.6737);
    hotStop = clamp(hotStop * min(1.0, lumaCap / max(hotLuma, 0.001)), 0.0, 1.0);
    // Secondary palette color, derived IN-SHADER from vertexColor via the
    // baked primary->secondary relation (hue angle + sat/value ratios) --
    // the vertex format has no second color attribute, and deriving both
    // from the live vertexColor keeps the owner recolor authoritative.
    vec3 secCol = clamp(satLift(clamp(hueSpin(baseCol, 0.7784), 0.0, 1.0), 0.9979) * 0.9457, 0.0, 1.0);

    // [layer:deep:parallax3d_caustic_x3]
    // Interior volume: correlated parallax PLANES of ONE deep field on
    // the 3D sphere direction, composited FRONT-TO-BACK under Beer-
    // Lambert transmittance -- each plane occludes the ones behind it,
    // and its light lands in BOTH the color accumulator (per-plane color
    // receding baseCol -> secCol -> dark stop) and the opacity term that
    // feeds the alpha. Farther planes show finer features, spin slower
    // (integer turns/day: the daily wrap lands on a full turn) and slide
    // along the TRUE view-tangent parallax direction (v11: par = Vt *
    // parScale replaces the old screen-space rimDir estimate -- planes
    // hold still head-on and shear apart toward the grazing limb).
    vec3 spinAxis = vec3(-0.6406, -0.5767, 0.5070);
    vec3 par = Vt * 1.8084;
    // v11 breathing: the deep domain slowly in/exhales (day-quantized,
    // well under 2 Hz) so the interior volume reads alive, not baked.
    float deepBreath = 1.0 + 0.0175 * sin(time * 1.460841);
    float deepTrans = 1.0;
    vec3 deepCol = vec3(0.0);
    float dp = deepField(rotA(spinAxis, time * 0.073304) * (sdir * (2.4298 * deepBreath)), time);
    deepCol += deepTrans * dp * baseCol;
    deepTrans *= 1.0 - 0.4360 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.068068) * (sdir * (3.2712 * deepBreath)) + par * 0.0571, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 0.6412), deepStop, 0.2351);
    deepTrans *= 1.0 - 0.4360 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.062832) * (sdir * (4.1126 * deepBreath)) + par * 0.1142, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 1.0000), deepStop, 0.4702);
    deepTrans *= 1.0 - 0.4360 * clamp(dp, 0.0, 1.0);
    deepCol *= 0.7627;
    float deepPat = pow(clamp((1.0 - deepTrans) * 1.2187, 0.0, 1.0), 1.4857);

    // [layer:mid:rings_none_pulse]
    // Signature structure of this effect, domain-warped and animated.
    float breathe = 1.0 + 0.0730 * sin(time * 0.743510);
    // only the y axis breathes; the x scale stays fixed so the u wrap
    // stays exact (the y period carries a margin for the stretch)
    vec2 auv = vec2(baseUV.x * 3.0000 + time * 0.290000, (baseUV.y - 0.5) * 3.0000 * breathe + 1.5000 + time * 0.091667);
    vec2 wuv = auv;
    float band = 0.5 + 0.5 * sin(baseUV.y * 29.0584 + time * 0.858702 + fbm2(wuv, midPer) * 1.7909);
    float rp = ringPulse(baseUV, time);
    float mid = pow(clamp(band, 0.0, 1.0), 2.1176) * 0.8 + rp * 0.5197;

    // [layer:tex:starfield]
    // Real sampled detail from atlas tile 8 (starfield), matched to this
    // family's technique. The INTEGER repeat multiplier keeps the lookup exact
    // across the u = 0/1 wrap (the domain spans an integer lattice period per
    // wrap, and its drifts shift integer periods per day -- day-wrap-safe);
    // the inset clamp keeps the linear-filtered sample inside this tile.
    // v9 family texture-drift: a baked per-FAMILY drift vector (direction
    // golden-angle-spread by family index, speed day-quantized against the
    // tile period) -- two families sharing a tile move it differently.
    vec2 texUV = wuv * 5.0000 + vec2(0.065000, -0.045000) * time;
    // v8 height taps: the atlas R/G/B structural mix doubles as a HEIGHT
    // field. Its 2-tap gradient (a) tilts the shading normal (bump) and
    // (b) builds the divergence-free flow vector the energy crawls along.
    vec3 hgtW = vec3(0.3766, 0.3788, 0.2446);
    float hgtC = dot(atlasTile(texUV).rgb, hgtW);
    float hgtX = dot(atlasTile(texUV + vec2(0.0165, 0.0)).rgb, hgtW);
    float hgtY = dot(atlasTile(texUV + vec2(0.0, 0.0165)).rgb, hgtW);
    vec2 atlasSlope = vec2(hgtX - hgtC, hgtY - hgtC);
    // [layer:flow:atlas_curl]
    // v8 dual-phase flow-map advection: two taps advected along the curl
    // of the height field at half-cycle-offset fract phases, crossfaded
    // by phase distance -- the energy visibly CRAWLS across the membrane.
    // The phase speed completes integer cycles per day (day-wrap-safe)
    // and the flow vector is a function of the seam-periodic texUV domain
    // (u = 0/1 safe by construction).
    vec2 flowVec = vec2(atlasSlope.y, -atlasSlope.x) * 3.2791;
    float flowA = fract(time * 0.051667);
    float flowB = fract(flowA + 0.5);
    vec4 atlas = mix(atlasTile(texUV + flowVec * flowA), atlasTile(texUV + flowVec * flowB), abs(flowA - 0.5) * 2.0);
    // v7 atlas pole fade: texUV is longitude-dependent, so at v = 0/1 the
    // tile would pinch into an apex rosette. Every atlas INFLUENCE (mid
    // lift, body grade, emission) fades to its no-atlas value at the caps.
    float atlasPoleW = smoothstep(0.02, 0.12, min(baseUV.y, 1.0 - baseUV.y));
    float texDetail = clamp(atlas.r * 0.5341 + atlas.g * 0.5373 + atlas.b * 0.3469, 0.0, 1.0);
    // near-black point-star tile: remap so the sparse stars actually
    // contribute detail instead of flattening the whole membrane
    texDetail = clamp(texDetail * 2.5133 + 0.1893, 0.0, 1.0);
    // the multi-scale texture layers modulate the signature and add a lift
    // that is mostly GATED through the family's own pattern (v7) -- the
    // signature stays dominant and dark palettes keep their dark gaps
    mid = clamp(mid * mix(1.0, 0.6115 + 0.5332 * texDetail, atlasPoleW) + 0.1919 * texDetail * (0.2519 + 0.7481 * clamp(mid, 0.0, 1.0)) * atlasPoleW, 0.0, 1.5);

    // [layer:normal:atlas_bump]
    // v8 perturbed shading normal: the atlas height gradient tilts the
    // analytic sphere normal along its tangent frame (dsdir/du, dsdir/dv).
    // Pole-faded: the u tangent degenerates at the caps, so the bump
    // scales with atlasPoleW and the normal falls back to sdir there.
    vec3 tanU = vec3(-sin(6.2831853 * baseUV.x), 0.0, cos(6.2831853 * baseUV.x));
    vec3 tanV = vec3(cos(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        -sin(3.1415927 * baseUV.y),
        cos(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    vec3 bumpN = normalize(sdir + (tanU * atlasSlope.x + tanV * atlasSlope.y) * (1.4601 * atlasPoleW));
    // fresnel rim (view angle against the bumped normal; viewV was
    // hoisted next to sdir in v11): the classic force-field edge glow;
    // abs() keeps the back faces consistent
    float fresnel = pow(1.0 - abs(dot(bumpN, viewV)), 3.1715);

    // [layer:thick:paratex]
    // v11 in-shell texture parallax: two EXTRA atlas taps stepped along
    // the view tangent projected onto the tangent frame (VtUV) sample
    // the tile as if suspended deeper INSIDE the glass -- the detail
    // visibly shifts against the surface as the view moves. Seam/day-
    // safe: the offset lives on the periodic texUV domain.
    vec2 VtUV = vec2(dot(Vt, tanU), dot(Vt, tanV));
    vec3 deepTexA = atlasTile(texUV + VtUV * 0.0589).rgb;
    vec3 deepTexB = atlasTile(texUV - VtUV * 0.0589).rgb;
    float deepTex = 0.5 * (dot(deepTexA, hgtW) + dot(deepTexB, hgtW));

    // [layer:thick:chord]
    // v11 volumetric thickness: the membrane is a shell of relative
    // thickness rho = 0.1832 (celestial material group) on the unit
    // sphere. chord = the view ray's path length through the shell,
    // normalized by the radial thickness and limb-clamped: chordN is
    // 1.0 head-on and saturates at 3.0 toward the grazing silhouette.
    // Two-case: while the ray still hits the inner sphere the path is
    // cosV - sqrt(disc); past the tangent ring it misses and runs the
    // full outer chord 2*cosV, capped at the inner-tangent maximum
    // 2*sqrt(1 - (1-rho)^2) = 1.1537.
    float cosV = abs(dot(sdir, viewV));
    float chordDisc = 0.8168 * 0.8168 - (1.0 - cosV * cosV);
    float chord = chordDisc > 0.0 ? cosV - sqrt(chordDisc) : min(2.0 * cosV, 1.1537);
    float chordN = min(chord / 0.1832, 3.0);

    // [layer:rim:graze_sparkle]
    // Silhouette / band lift so the membrane reads as a curved shell:
    // a wide soft inner glow (style-specific) plus a thin hot line at
    // the very edge. The slope is normalized by the camera distance so
    // the rim width stays view-consistent near and far.
    float rimSlope = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    float rimLine = smoothstep(0.0544, 0.0941, rimSlope);
    float rimGlint = sparkle(baseUV * 18.0000, time, 18.0000);
    float rim = rimGraze() * 0.8702 * (0.7 + 0.6 * rimGlint) + 0.5211 * rimGlint;
    // v8: the fresnel term folds into the rim glow -- edges glow, the
    // center stays refraction-dominated (see the [layer:refract] mix).
    rim = clamp(rim + 0.7022 * rimLine + 0.8008 * fresnel, 0.0, 1.4);

    // Flourish accent + micro grain keep large areas alive up close.
    float flourish = 0.1424 * caustic(wuv + vec2(3.1, 8.7), vec2(0.197500, -0.120833) * time, midPer);
    float grain = 0.0597 * (cellHash(floor(wuv * 29.0000) + vec2(floor(time * 2.0), 0.0), 87.0000) - 0.5);

    // [layer:motif:core:breath]
    // v9 per-id motif fingerprint: this effect's unique moving bright
    // element (core x1) under its breath emissive envelope.
    float motifEnv = 0.72 + 0.28 * sin(time * 0.685914 + 5.9924);
    vec2 motifC = vec2(sin((baseUV.x - 0.5) * 3.1415927) * 0.6366, baseUV.y - 0.5);
    float motifR = length(motifC);
    float motifM = exp(-motifR * motifR * 18.4009) * (0.75 + 0.25 * sin(time * 0.691150 + 4.5257));
    float motifGlow = clamp(motifM, 0.0, 1.2) * motifEnv;

    // Recolor-safe composite v4: the whole pattern is graded through the
    // vertexColor-derived 3-stop ramp (low pattern falls to the DARK stop
    // and low alpha -- never pale grey), the deep volume sits BEHIND the
    // signature structure, and the gradient position leans toward the hot
    // stop at the rim (chromatic rim). The vertexColor.a dissolve near
    // whitelisted players always wins the final alpha.
    float pattern = clamp(0.3295 * deepPat * mix(1.0, chordN, 0.2232) + 0.8642 * mid + 0.5505 * rim + flourish + grain + 0.1157 * deepTex, 0.0, 1.5);
    float gpos = clamp(pattern * 0.8935 + rim * 0.2535, 0.0, 1.0);
    vec3 rgb = gradient3(deepStop, baseCol, hotStop, gpos);
    float midCover = clamp(1.1087 * mid + 0.6196 * rim, 0.0, 1.0);
    rgb = mix(deepCol, rgb, midCover);
    // [layer:tex:body] -- the sampled multi-scale detail also grades the
    // composited body (deep volume included). v7: the grade is pole-faded
    // and partly gated through the pattern, so the family signature stays
    // dominant over the tile texture and the caps keep their clean body.
    float texBody = 0.8237 + 0.4309 * texDetail;
    rgb *= mix(1.0, texBody, atlasPoleW * (0.5393 + 0.4607 * clamp(pattern, 0.0, 1.0)));
    rgb = satLift(rgb, 1.2960);
    // Hue-preserving soft-clip on the hot crests: brightness saturates
    // toward the palette's own bright tint (1 - exp(-k * hotStop * x)),
    // never toward additive white -- rich color instead of pastel.
    vec3 softHot = 1.0 - exp(-3.2622 * hotStop * (pattern + 0.35 * rim));
    rgb = mix(rgb, softHot, 0.2378 * smoothstep(0.55, 1.10, pattern));
    vec3 accent = accentPalette(0.6822 + pattern * 0.4319);
    rgb = mix(rgb, rgb * (0.55 + 0.9 * accent), 0.4174);
    // Two-band chromatic dispersion on the rim (thin-film-like), biased
    // to vertexColor.rgb: band 1 multiplies the wide glow into the
    // palette-driven rgb, band 2 pulls the thin hot line toward the (also
    // vertexColor-derived) hot stop. Both bounded -- the owner recolor
    // override stays authoritative on every rim style.
    vec3 rimDisp = 0.5 + 0.5 * cos(vec3(1.0, 0.8065, 0.6452) * (rim * 0.7504 + baseUV.y * 0.6292 + 0.2436) * 6.2831853);
    rgb = mix(rgb, rgb * (0.72 + 0.56 * rimDisp), clamp(rim, 0.0, 1.0) * 0.1635);
    vec3 lineDisp = 0.5 + 0.5 * cos(vec3(0.6452, 0.8065, 1.0) * (rimLine * 0.5334 + baseUV.y * 0.31 + 0.3157) * 6.2831853);
    rgb = mix(rgb, hotStop * (0.62 + 0.50 * lineDisp), clamp(rimLine, 0.0, 1.0) * 0.2962);
    // [layer:wash:high_luma]
    // v10 near-white wash guard: near-white/high-luma palettes (chrome,
    // crystal) still washed to white at the apex under the linear per-luma
    // guards, so a smoothstep factor cuts the specular add, the emissive
    // add/white-mix and the energy overlay much harder for bright palettes
    // ONLY, and darkens the low-pattern body so structure shows. Recolor-
    // safe: washHi derives from the live vertexColor luma, nothing baked.
    float baseLuma = dot(baseCol, vec3(0.299, 0.587, 0.114));
    float washHi = smoothstep(0.55, 0.85, baseLuma);
    // uniform pre-clip compression + extra darkening of the low-pattern
    // body: near-white crests otherwise all clip to 1.0 and flatten into
    // one white sheet at the apex.
    rgb *= (1.0 - 0.2969 * washHi) * (1.0 - 0.2567 * washHi * (1.0 - clamp(pattern, 0.0, 1.0)));
    // [layer:light:wrapkey]
    // v8 fake lighting: wrap-diffuse + specular from a FIXED world key
    // light against the bumped normal, applied to the ENERGY only (the
    // refracted scene below is already lit). Recolor-safe: the diffuse is
    // a bounded multiplicative grade and the specular adds the palette's
    // own luma-capped hot stop -- no baked hue anywhere.
    vec3 keyL = vec3(0.0782, 0.9955, 0.0538);
    float keyDiff = clamp((dot(bumpN, keyL) + 0.4125) / 1.4125, 0.0, 1.0);
    rgb *= 0.6661 + 0.6399 * keyDiff * (1.0 - 0.5630 * washHi);
    float keySpec = pow(clamp(dot(reflect(-viewV, bumpN), keyL), 0.0, 1.0), 23.9315);
    rgb += hotStop * (keySpec * 0.2810 * (1.0 - 0.5954 * washHi));
    // [layer:glass:beer]
    // W6/1.21.1 glass composite: no scene copy on this target, so the
    // real world shows through the TRANSLUCENT blend (see the glass
    // alpha floor below) instead of a refracted scene sample. What
    // survives from the 26.2 refraction layer is the Beer-Lambert
    // chord absorption -- the glass base color is the live palette
    // absorbed along the view path through the shell, so grazing
    // paths tint deeper and stay in-hue (recolor-safe) -- and the
    // energy weight, which still balances the family's pattern
    // against the see-through glass base: gaps read as tinted glass
    // over the alpha-blended world, features as energy, edges glow.
    vec3 glassCol = baseCol * exp(-0.6062 * chordN * (1.0 - baseCol));
    glassCol *= mix(vec3(1.0), baseCol, 0.3126);
    float energyW = clamp(0.2351 + 0.4461 * clamp(pattern, 0.0, 1.0) + 0.2207 * fresnel, 0.0, 0.8662);
    // v10 wash guard on the overlay: white palettes show MORE glass
    // (and world) instead of piling white energy on white glass.
    energyW *= 1.0 - 0.2915 * washHi;
    rgb = mix(glassCol, rgb, energyW);
    rgb += fresnel * hotStop * (1.1946 * (1.0 - 0.6766 * washHi));
    // v9 motif add: the per-id moving bright element rides ON TOP of the
    // energy-glass composite so the fingerprint stays identifiable.
    // Recolor-safe: its color is a hotStop/secCol mix, both live-derived
    // from vertexColor; its envelope is <= 2 Hz and day-quantized.
    rgb += motifGlow * mix(hotStop, secCol, 0.3918) * 0.9425;
    // [layer:emit:atlas_a]
    // Emissive glow: atlas.a is an EMISSION mask (never transparency) --
    // filament cores / cell edges / cracks / sparkles ADD a bright, hue-
    // preserving tint of the live palette. v7 wash guard: both the white-
    // mix and the emissive gain fall off with the palette's own luma, so
    // bright palettes (chrome/pastel) glow IN HUE instead of blowing to
    // white, while dark palettes keep their full glow. Scaled by the
    // family's own highlights and a slow day-quantized breath -- the glow
    // is spatial and strobe-free by construction.
    // (baseLuma/washHi were computed in the v10 wash-guard layer above;
    // washHi additionally cuts the white-mix AND the emissive add for
    // near-white palettes -- they glow in hue, never toward white.)
    vec3 emitCol = clamp(mix(baseCol, vec3(1.0), 0.3541 * max(0.0, 1.0 - 0.5796 * baseLuma - 0.5111 * washHi)), 0.0, 1.0);
    // near-black point-star tile: boost the sparse emission mask so the
    // star families are not left flat
    float emitMask = clamp(atlas.a * 1.8970, 0.0, 1.0);
    float emit = emitMask * (0.3301 + 0.6735 * clamp(pattern, 0.0, 1.0)) * (1.0 - 0.1642 * (0.5 + 0.5 * sin(time * 0.130900))) * atlasPoleW;
    rgb += emit * 0.7723 * (1.0 - 0.6562 * baseLuma) * (1.0 - 0.4299 * washHi) * emitCol;
    // [layer:wash:knee]
    // v10 washHi-gated soft-knee: for near-white palettes every additive
    // path (fresnel glow, motif, emission, specular) lands >= 1.0 and CLIPS,
    // flattening the apex into one white sheet -- compress the overshoot
    // exponentially instead so crest/gap structure survives up to white.
    // Identity for dark palettes (washHi = 0 -> knee = 1.0).
    float washKnee = 1.0 - 0.2441 * washHi;
    vec3 washOver = max(rgb - vec3(washKnee), vec3(0.0));
    rgb = min(rgb, vec3(washKnee)) + (1.0 - washKnee) * (1.0 - exp(-washOver * 4.8125));
    // Presence BODY alpha (family-tuned, v6 solidity lift): a firm membrane
    // base even between features, a solid floor wherever the pattern is
    // present, rising toward the ceiling on bright features, plus the deep
    // volume's Beer-Lambert opacity and the emissive glow. v7 dissolve
    // authority: EVERY alpha modifier (emission, back-face densify, ghost
    // thinning, dither) acts on this body value, which is clamped to the
    // family ceiling and only THEN multiplied by vertexColor.a -- the
    // whitelisted-player dissolve is always the final, outermost factor.
    float presence = smoothstep(0.02, 0.30, pattern);
    float bodyAlpha = 0.3663 + 0.4439 * presence + 0.4571 * pattern + 0.1171 * (1.0 - deepTrans) + 0.1744 * emit;
    // v9: the motif also firms the membrane locally (pre-clamp, pre-
    // dissolve -- vertexColor.a still always wins).
    bodyAlpha += motifGlow * 0.1808;
    // [layer:inner:stars]
    // v11 far-shell interior: with the mesh's inward winding and cull OFF,
    // gl_FrontFacing is TRUE exactly where the camera sees the concave side
    // (the far shell from outside, the whole wall from inside).
    float innerFace = gl_FrontFacing ? 1.0 : 0.0;
    // INNER_PARALLAX_STARS: the deep field re-sampled at plane-0 scale
    // on a SLOWED rotation (0.8x re-rounded turns) with a view-tangent
    // offset -- a star shell parallaxing behind the surface.
    float innerStar = deepField(rotA(spinAxis, time * 0.052360 + 4.7297) * (sdir * 2.4298) + Vt * 0.4374, time);
    float innerLit = pow(clamp(innerStar, 0.0, 1.0), 1.6996);
    vec3 innerCol = mix(deepStop, mix(secCol, hotStop, 0.5982), innerLit);
    rgb = mix(rgb, innerCol, innerFace * 0.2634);
    bodyAlpha *= 1.0 + innerFace * 0.2113;
    // [layer:alpha:glassfloor]
    // W6/1.21.1 glass alpha floor, folded into bodyAlpha BEFORE the
    // ceiling clamp: the 26.2 near-opaque refraction floor becomes a
    // TRANSLUCENT floor -- the world behind the membrane is revealed by
    // the alpha blend now, so the gaps must stay genuinely see-through.
    // (No depth-soft fade either: that needed the scene depth copy.)
    bodyAlpha = max(bodyAlpha, 0.3896);
    // dissolve authority: clamp the body to the family ceiling FIRST, then
    // apply the whitelisted-player dissolve as the LAST alpha operation --
    // no path can push the final alpha above vertexColor.a * ceiling.
    float alpha = clamp(bodyAlpha, 0.0, 0.8723) * vertexColor.a;
    vec4 color = vec4(clamp(rgb, 0.0, 1.0), alpha);
    if (color.a < 0.01) {
        discard;
    }
    // vanilla 1.21.1 fog: linear_fog over the FogShape-picked distance
    // metric, exactly like the vanilla core shaders' fog_distance(pos,
    // FogShape) split across the two precomputed varyings.
    fragColor = linear_fog(color, FogShape == 0 ? sphericalVertexDistance : cylindricalVertexDistance, FogStart, FogEnd, FogColor);
}
