#version 150

#moj_import <fog.glsl>

// The shipped surface atlas (bubbleshield:textures/effect/surface_atlas.png,
// bound by ShieldPipelines' per-effect RenderType through its
// TextureStateShard): an 8x4 grid of 32 seamless grayscale tiles. Per texel:
// R = coarse structure, G = mid detail, B = fine grain, A = EMISSION mask
// (glow, NOT transparency). All hue comes from vertexColor at runtime
// (recolor-safe).
uniform sampler2D Sampler0;
// Vanilla auto-filled uniforms (declared in fx_NNN.json; ShaderInstance
// .setDefaultUniforms fills them every draw). GameTime spans one day cycle
// in [0, 1); FogShape picks the vanilla fog metric (0 = spherical).
uniform float GameTime;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;
uniform int FogShape;

// Bubble surface shader fx_366 -- family HOLOGRID
// stack: deep=ridge x3 taps | mid=hologrid+warp1+rotate | rim=graze_sparkle | flourish=glint | tex=riveted_plates | motif=sigilx3+breath
// fbm: turb x3 octaves | seed 9bbcaf6628295e79
// v12 realism (1.21.1): glass tint 0.3071+Beer 0.4085*chord | energy 0.2330+0.3954*p | flow 0.065000 c/s | floor 0.3770
// GENERATED by tools/gen_surface_shaders.py -- do not hand-edit; edit the
// generator and regenerate instead (byte-stable, fixed seed).

in vec2 texCoord0;
in vec4 vertexColor;
in float sphericalVertexDistance;
in float cylindricalVertexDistance;
// Camera-relative world-space position from surface.vsh: the camera is
// the origin of this space, so view direction = -normalize(worldPos).
in vec3 worldPos;

out vec4 fragColor;

// 1 - smoothstep with ASCENDING edges. Replaces every reversed-edge
// smoothstep(hi, lo, x) call: edge0 >= edge1 is undefined by the GLSL
// spec; this form is numerically identical on conforming drivers.
float invsmooth(float lo, float hi, float x) {
    return 1.0 - smoothstep(lo, hi, x);
}

// Rodrigues rotation matrix around a baked unit axis. Driven with an
// angle that completes an INTEGER number of turns per day, the daily
// time wrap 1200 -> 0 lands exactly on a full turn -- the catalogue's
// first true (non-shear) rotation animation, only legal on the 3D
// sphere-direction domain (a 2D UV rotation would break the u wrap).
mat3 rotA(vec3 axis, float a) {
    float s = sin(a);
    float c = cos(a);
    float oc = 1.0 - c;
    return mat3(
        oc * axis.x * axis.x + c, oc * axis.x * axis.y + axis.z * s, oc * axis.z * axis.x - axis.y * s,
        oc * axis.x * axis.y - axis.z * s, oc * axis.y * axis.y + c, oc * axis.y * axis.z + axis.x * s,
        oc * axis.z * axis.x + axis.y * s, oc * axis.y * axis.z - axis.x * s, oc * axis.z * axis.z + c);
}

float hash21(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

// Hoskins-style 3D->1D hash; small multiplier keeps fp32 precision
// alive over the whole sphere-direction domain
float hash31(vec3 p3) {
    p3 = fract(p3 * 0.1031);
    p3 += dot(p3, p3.zyx + 31.32);
    return fract((p3.x + p3.y) * p3.z);
}

// lattice-cell hash that tiles across the longitude seam: the cell's
// x id wraps every px cells, so u = 0 and u = 1 sample identical cells
float cellHash(vec2 cellId, float px) {
    return hash21(vec2(mod(cellId.x, px), cellId.y));
}

// value noise on a wrapping lattice (quintic fade): 'per' tiles the
// field so it is seamless across the u = 0/1 longitude wrap
float vnoise(vec2 p, vec2 per) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float a = hash21(mod(i, per));
    float b = hash21(mod(i + vec2(1.0, 0.0), per));
    float cc = hash21(mod(i + vec2(0.0, 1.0), per));
    float d = hash21(mod(i + vec2(1.0, 1.0), per));
    return mix(mix(a, b, u.x), mix(cc, d, u.x), u.y);
}

// 3D value noise (quintic fade). Sampled on the sphere direction the
// domain is periodic across the u seam AND uniform at the poles by
// construction, so unlike the 2D lattice it needs NO wrap period.
float vnoise3(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    vec3 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float n000 = hash31(i);
    float n100 = hash31(i + vec3(1.0, 0.0, 0.0));
    float n010 = hash31(i + vec3(0.0, 1.0, 0.0));
    float n110 = hash31(i + vec3(1.0, 1.0, 0.0));
    float n001 = hash31(i + vec3(0.0, 0.0, 1.0));
    float n101 = hash31(i + vec3(1.0, 0.0, 1.0));
    float n011 = hash31(i + vec3(0.0, 1.0, 1.0));
    float n111 = hash31(i + vec3(1.0, 1.0, 1.0));
    return mix(mix(mix(n000, n100, u.x), mix(n010, n110, u.x), u.y),
        mix(mix(n001, n101, u.x), mix(n011, n111, u.x), u.y), u.z);
}

// fractal noise, turb mode, 3 octaves. The x lacunarity
// is exactly 2 and the lattice period doubles with it, so EVERY octave
// tiles the longitude seam (a rotation here would break the wrap).
float fbm2(vec2 p, vec2 per) {
    float value = 0.0;
    float amplitude = 0.5;
    for (int i = 0; i < 3; i++) {
        value += amplitude * abs(2.0 * vnoise(p, per) - 1.0);
        p = vec2(p.x * 2.0, p.y * 2.0772) + vec2(17.7, 9.2);
        per = vec2(per.x * 2.0, per.y * 2.0772);
        amplitude *= 0.5;
    }
    return value;
}

// 3D fractal noise, turb mode, 3 octaves (budget: <= 4 --
// each octave costs 8 hashes). No wrap bookkeeping: the sphere-
// direction domain is seam- and pole-free by construction.
float fbm3(vec3 p) {
    float value = 0.0;
    float amplitude = 0.5;
    for (int i = 0; i < 3; i++) {
        value += amplitude * abs(2.0 * vnoise3(p) - 1.0);
        p = p * 2.0 + vec3(11.7, 5.3, 7.1);
        amplitude *= 0.5;
    }
    return value;
}

// iq single-stage domain warp: f(p + h(p)). The offset field is seam-
// periodic, so warping preserves the u wrap; drifts are day-quantized.
vec2 warp1(vec2 p, vec2 per, float t) {
    return p + 0.7679 * (vec2(fbm2(p + vec2(0.0, t * 0.310000), per),
        fbm2(p + vec2(5.2, 1.3) - vec2(t * 0.266667, 0.0), per)) - 0.5);
}

// iq cosine palette, baked per effect; used ONLY for bounded accents
vec3 accentPalette(float t) {
    return vec3(0.5) + vec3(0.5) * cos(6.2831853 * (vec3(0.9090, 1.1757, 1.1070) * t
        + vec3(0.2322, 0.5489, 0.8604)));
}

// 3-stop shadow/body/highlight grade (two smoothstep segments): every
// stop is derived from vertexColor.rgb at RUNTIME, so the owner /color
// override recolors shadow, body and highlight together (recolor-safe
// by construction).
vec3 gradient3(vec3 deepStop, vec3 body, vec3 hotStop, float x) {
    vec3 g = mix(deepStop, body, smoothstep(0.0, 0.4039, x));
    return mix(g, hotStop, smoothstep(0.4039, 1.0, x));
}

// saturation lift: mixes AWAY from luma (s > 1), deepening the chroma
// without changing the hue -- the anti-washout pass
vec3 satLift(vec3 col, float s) {
    float l = dot(col, vec3(0.299, 0.587, 0.114));
    return clamp(mix(vec3(l), col, s), 0.0, 1.0);
}

// Rodrigues rotation of the color vector around the grey axis; nudges
// the highlight stop's hue away from the body color. The input is
// always derived from vertexColor.rgb at runtime, so recolor-safe.
vec3 hueSpin(vec3 col, float a) {
    const vec3 k = vec3(0.57735027);
    float ca = cos(a);
    float sa = sin(a);
    return col * ca + cross(k, col) * sa + k * dot(k, col) * (1.0 - ca);
}

// silhouette estimator: the camera-distance varying changes fastest per
// pixel at grazing angles, so fwidth() peaks at the bubble's rim.
// Normalizing by the distance itself keeps the rim width roughly
// view-consistent near and far.
float rimGraze() {
    float g = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    return smoothstep(0.0051, 0.0568, g);
}

// hash-cell twinkle: sparse offset star points with per-cell phase;
// cells wrap every px in x so the field tiles the u seam
float sparkle(vec2 p, float t, float px) {
    vec2 cellId = floor(p);
    vec2 f = fract(p) - 0.5;
    float h = cellHash(cellId, px);
    vec2 off = vec2(cellHash(cellId + 11.3, px), cellHash(cellId + 27.9, px)) - 0.5;
    float d = length(f - off * 0.55);
    float tw = pow(0.5 + 0.5 * sin(t * (2.0 + 5.0 * h) + h * 39.0), 6.0);
    return step(0.7389, h) * invsmooth(0.02, 0.22, d) * tw;
}

// one inset-clamped tap of this file's surface-atlas tile: fract()
// wraps the (seam-periodic) repeat domain, and the inset keeps the
// linear-filtered lookup inside the tile for ANY flow/gradient offset
// (8x4 tile grid -> per-axis scale vec2(0.125, 0.25))
vec4 atlasTile(vec2 p) {
    return texture(Sampler0, (vec2(4.0000, 3.0000) + clamp(fract(p), 0.004, 0.996)) * vec2(0.125, 0.25));
}

// DEEP-layer field (3D ridged crest volume), sampled on the 3D sphere direction by
// the correlated parallax planes -- seam- and pole-free
float deepField(vec3 p, float t) {
    float n = fbm3(p);
    return pow(1.0 - abs(2.0 * n - 1.0), 2.3424);
}

void main() {
    // GameTime spans one day cycle in [0, 1); scale to roughly seconds.
    // All constant speeds below are day-quantized (integer cycles or
    // integer lattice periods per day) so the daily wrap does not pop.
    float time = GameTime * 1200.0;
    // texCoord0 is the raw sphere UV, already in [0,1]; fract() is only a
    // defensive wrap. Seam-freedom in u comes from the wrapping-lattice /
    // periodic-domain sampling below, NOT from this fract().
    vec2 baseUV = fract(texCoord0);
    vec2 midPer = vec2(10.0000, 12.0000);
    // 3D sphere direction reconstructed from the UV (u -> longitude,
    // v -> latitude): any field sampled on it is periodic across the
    // u = 0/1 seam AND uniform at the poles by construction.
    vec3 sdir = vec3(sin(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        cos(3.1415927 * baseUV.y),
        sin(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    // v11: the view direction is hoisted up here (the thickness and
    // parallax layers need it before the normal block) together with
    // its component TANGENT to the shell surface: Vt is the true
    // parallax direction -- zero head-on, maximal at the grazing limb,
    // seam-safe by construction (pure 3D geometry, no UV involved).
    vec3 viewV = -normalize(worldPos);
    vec3 Vt = viewV - dot(viewV, sdir) * sdir;

    // [palette:gradient3]
    // Runtime 3-stop palette derived from vertexColor.rgb: the dark stop
    // darkens AND saturates (base*base stays in-hue instead of greying);
    // the hot stop is a LUMA-CAPPED CHROMATIC highlight -- a hue-nudged,
    // saturation-lifted, brightened base whose luma is capped relative to
    // the base luma, so the highlight can NEVER wash out toward white.
    // The owner /color override replaces vertexColor wholesale, so the
    // whole ramp re-derives from it -- recolor-safe by construction.
    vec3 baseCol = vertexColor.rgb;
    vec3 deepStop = baseCol * baseCol * 0.7544;
    vec3 spun = clamp(hueSpin(baseCol, -0.2584), 0.0, 1.0);
    vec3 hotStop = satLift(spun, 1.3182) * 1.45;
    float hotLuma = dot(hotStop, vec3(0.299, 0.587, 0.114));
    float lumaCap = max(0.4956, dot(baseCol, vec3(0.299, 0.587, 0.114)) * 1.5901);
    hotStop = clamp(hotStop * min(1.0, lumaCap / max(hotLuma, 0.001)), 0.0, 1.0);
    // Secondary palette color, derived IN-SHADER from vertexColor via the
    // baked primary->secondary relation (hue angle + sat/value ratios) --
    // the vertex format has no second color attribute, and deriving both
    // from the live vertexColor keeps the owner recolor authoritative.
    vec3 secCol = clamp(satLift(clamp(hueSpin(baseCol, 0.1396), 0.0, 1.0), 0.9455) * 0.3000, 0.0, 1.0);

    // [layer:deep:parallax3d_ridge_x3]
    // Interior volume: correlated parallax PLANES of ONE deep field on
    // the 3D sphere direction, composited FRONT-TO-BACK under Beer-
    // Lambert transmittance -- each plane occludes the ones behind it,
    // and its light lands in BOTH the color accumulator (per-plane color
    // receding baseCol -> secCol -> dark stop) and the opacity term that
    // feeds the alpha. Farther planes show finer features, spin slower
    // (integer turns/day: the daily wrap lands on a full turn) and slide
    // along the TRUE view-tangent parallax direction (v11: par = Vt *
    // parScale replaces the old screen-space rimDir estimate -- planes
    // hold still head-on and shear apart toward the grazing limb).
    vec3 spinAxis = vec3(-0.6178, 0.4526, 0.6430);
    vec3 par = Vt * 1.7225;
    // v11 breathing: the deep domain slowly in/exhales (day-quantized,
    // well under 2 Hz) so the interior volume reads alive, not baked.
    float deepBreath = 1.0 + 0.0144 * sin(time * 2.136283);
    float deepTrans = 1.0;
    vec3 deepCol = vec3(0.0);
    float dp = deepField(rotA(spinAxis, time * 0.068068) * (sdir * (1.7435 * deepBreath)), time);
    deepCol += deepTrans * dp * baseCol;
    deepTrans *= 1.0 - 0.5113 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.062832) * (sdir * (2.6869 * deepBreath)) + par * 0.0564, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 0.5973), deepStop, 0.2190);
    deepTrans *= 1.0 - 0.5113 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.052360) * (sdir * (3.6304 * deepBreath)) + par * 0.1127, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 1.0000), deepStop, 0.4380);
    deepTrans *= 1.0 - 0.5113 * clamp(dp, 0.0, 1.0);
    deepCol *= 0.7538;
    float deepPat = pow(clamp((1.0 - deepTrans) * 1.1321, 0.0, 1.0), 1.0366);

    // [layer:mid:hologrid_warp1_rotate]
    // Signature structure of this effect, domain-warped and animated.
    // seam-safe stand-in for domain rotation: true rotation would mix
    // latitude into longitude and break the u wrap, so the pattern
    // leans (shears) back and forth instead.
    float sway = 0.5692 * sin(time * 0.109956);
    vec2 auv = vec2(baseUV.x * 10.0000 + (baseUV.y - 0.5) * sway + time * -0.091667, baseUV.y * 10.0000);
    vec2 wuv = warp1(auv, midPer, time);
    float lonLine = pow(abs(sin(baseUV.x * 3.1415927 * 12.0000)), 10.5772);
    float latLine = pow(abs(sin(baseUV.y * 3.1415927 * 8.0000)), 9.5609);
    float scanPos = fract(time * 0.056667);
    float scan = invsmooth(0.0, 0.1310, abs(baseUV.y - scanPos));
    float glint = step(0.82, cellHash(floor(vec2(baseUV.x * 12.0000, baseUV.y * 8.0000)), 12.0000)) * lonLine * latLine;
    float holoFlicker = 0.94 + 0.06 * sin(time * 6.581637);
    float holoSteady = (lonLine + latLine) * 0.7295;
    float mid = clamp(holoSteady * holoFlicker + scan * 0.3726 + glint * 0.9, 0.0, 1.25);

    // [layer:tex:riveted_plates]
    // Real sampled detail from atlas tile 28 (riveted_plates), matched to this
    // family's technique. The INTEGER repeat multiplier keeps the lookup exact
    // across the u = 0/1 wrap (the domain spans an integer lattice period per
    // wrap, and its drifts shift integer periods per day -- day-wrap-safe);
    // the inset clamp keeps the linear-filtered sample inside this tile.
    // v9 family texture-drift: a baked per-FAMILY drift vector (direction
    // golden-angle-spread by family index, speed day-quantized against the
    // tile period) -- two families sharing a tile move it differently.
    vec2 texUV = wuv * 1.0000 + vec2(-0.032500, -0.034167) * time;
    // v8 height taps: the atlas R/G/B structural mix doubles as a HEIGHT
    // field. Its 2-tap gradient (a) tilts the shading normal (bump) and
    // (b) builds the divergence-free flow vector the energy crawls along.
    vec3 hgtW = vec3(0.4184, 0.2544, 0.3273);
    float hgtC = dot(atlasTile(texUV).rgb, hgtW);
    float hgtX = dot(atlasTile(texUV + vec2(0.0192, 0.0)).rgb, hgtW);
    float hgtY = dot(atlasTile(texUV + vec2(0.0, 0.0192)).rgb, hgtW);
    vec2 atlasSlope = vec2(hgtX - hgtC, hgtY - hgtC);
    // [layer:flow:atlas_curl]
    // v8 dual-phase flow-map advection: two taps advected along the curl
    // of the height field at half-cycle-offset fract phases, crossfaded
    // by phase distance -- the energy visibly CRAWLS across the membrane.
    // The phase speed completes integer cycles per day (day-wrap-safe)
    // and the flow vector is a function of the seam-periodic texUV domain
    // (u = 0/1 safe by construction).
    vec2 flowVec = vec2(atlasSlope.y, -atlasSlope.x) * 2.8920;
    float flowA = fract(time * 0.065000);
    float flowB = fract(flowA + 0.5);
    vec4 atlas = mix(atlasTile(texUV + flowVec * flowA), atlasTile(texUV + flowVec * flowB), abs(flowA - 0.5) * 2.0);
    // v7 atlas pole fade: texUV is longitude-dependent, so at v = 0/1 the
    // tile would pinch into an apex rosette. Every atlas INFLUENCE (mid
    // lift, body grade, emission) fades to its no-atlas value at the caps.
    float atlasPoleW = smoothstep(0.02, 0.12, min(baseUV.y, 1.0 - baseUV.y));
    float texDetail = clamp(atlas.r * 0.5364 + atlas.g * 0.3261 + atlas.b * 0.4195, 0.0, 1.0);
    // the multi-scale texture layers modulate the signature and add a lift
    // that is mostly GATED through the family's own pattern (v7) -- the
    // signature stays dominant and dark palettes keep their dark gaps
    mid = clamp(mid * mix(1.0, 0.6333 + 0.7056 * texDetail, atlasPoleW) + 0.1735 * texDetail * (0.2755 + 0.7245 * clamp(mid, 0.0, 1.0)) * atlasPoleW, 0.0, 1.5);

    // [layer:normal:atlas_bump]
    // v8 perturbed shading normal: the atlas height gradient tilts the
    // analytic sphere normal along its tangent frame (dsdir/du, dsdir/dv).
    // Pole-faded: the u tangent degenerates at the caps, so the bump
    // scales with atlasPoleW and the normal falls back to sdir there.
    vec3 tanU = vec3(-sin(6.2831853 * baseUV.x), 0.0, cos(6.2831853 * baseUV.x));
    vec3 tanV = vec3(cos(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        -sin(3.1415927 * baseUV.y),
        cos(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    vec3 bumpN = normalize(sdir + (tanU * atlasSlope.x + tanV * atlasSlope.y) * (1.2669 * atlasPoleW));
    // fresnel rim (view angle against the bumped normal; viewV was
    // hoisted next to sdir in v11): the classic force-field edge glow;
    // abs() keeps the back faces consistent
    float fresnel = pow(1.0 - abs(dot(bumpN, viewV)), 3.4062);

    // [layer:thick:paratex]
    // v11 in-shell texture parallax: two EXTRA atlas taps stepped along
    // the view tangent projected onto the tangent frame (VtUV) sample
    // the tile as if suspended deeper INSIDE the glass -- the detail
    // visibly shifts against the surface as the view moves. Seam/day-
    // safe: the offset lives on the periodic texUV domain.
    vec2 VtUV = vec2(dot(Vt, tanU), dot(Vt, tanV));
    vec3 deepTexA = atlasTile(texUV + VtUV * 0.0691).rgb;
    vec3 deepTexB = atlasTile(texUV - VtUV * 0.0691).rgb;
    float deepTex = 0.5 * (dot(deepTexA, hgtW) + dot(deepTexB, hgtW));

    // [layer:thick:chord]
    // v11 volumetric thickness: the membrane is a shell of relative
    // thickness rho = 0.0690 (geo material group) on the unit
    // sphere. chord = the view ray's path length through the shell,
    // normalized by the radial thickness and limb-clamped: chordN is
    // 1.0 head-on and saturates at 3.0 toward the grazing silhouette.
    // Two-case: while the ray still hits the inner sphere the path is
    // cosV - sqrt(disc); past the tangent ring it misses and runs the
    // full outer chord 2*cosV, capped at the inner-tangent maximum
    // 2*sqrt(1 - (1-rho)^2) = 0.7302.
    float cosV = abs(dot(sdir, viewV));
    float chordDisc = 0.9310 * 0.9310 - (1.0 - cosV * cosV);
    float chord = chordDisc > 0.0 ? cosV - sqrt(chordDisc) : min(2.0 * cosV, 0.7302);
    float chordN = min(chord / 0.0690, 3.0);

    // [layer:rim:graze_sparkle]
    // Silhouette / band lift so the membrane reads as a curved shell:
    // a wide soft inner glow (style-specific) plus a thin hot line at
    // the very edge. The slope is normalized by the camera distance so
    // the rim width stays view-consistent near and far.
    float rimSlope = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    float rimLine = smoothstep(0.0470, 0.0704, rimSlope);
    float rimGlint = sparkle(baseUV * 12.0000, time, 12.0000);
    float rim = rimGraze() * 0.9245 * (0.7 + 0.6 * rimGlint) + 0.5749 * rimGlint;
    // v8: the fresnel term folds into the rim glow -- edges glow, the
    // center stays refraction-dominated (see the [layer:refract] mix).
    rim = clamp(rim + 0.8687 * rimLine + 0.6743 * fresnel, 0.0, 1.4);

    // Flourish accent + micro grain keep large areas alive up close.
    float flourish = 0.3253 * sparkle(wuv * 2.0 + 7.7, time * 1.4, midPer.x * 2.0);
    float grain = 0.0774 * (cellHash(floor(wuv * 26.0000) + vec2(floor(time * 2.0), 0.0), 260.0000) - 0.5);

    // [layer:motif:sigil:breath]
    // v9 per-id motif fingerprint: this effect's unique moving bright
    // element (sigil x3) under its breath emissive envelope.
    float motifEnv = 0.72 + 0.28 * sin(time * 0.570723 + 1.8788);
    float motifA = baseUV.x * 7.0000 + -1.0 * time * 0.045833 + 0.8903;
    float motifSig = pow(0.5 + 0.5 * cos(6.2831853 * motifA), 15.1965);
    float motifDy = (baseUV.y - 0.5394) * 7.5038;
    float motifBand = exp(-motifDy * motifDy);
    float motifM = motifSig * motifBand;
    float motifGlow = clamp(motifM, 0.0, 1.2) * motifEnv;

    // Recolor-safe composite v4: the whole pattern is graded through the
    // vertexColor-derived 3-stop ramp (low pattern falls to the DARK stop
    // and low alpha -- never pale grey), the deep volume sits BEHIND the
    // signature structure, and the gradient position leans toward the hot
    // stop at the rim (chromatic rim). The vertexColor.a dissolve near
    // whitelisted players always wins the final alpha.
    float pattern = clamp(0.4980 * deepPat * mix(1.0, chordN, 0.3049) + 0.8458 * mid + 0.7724 * rim + flourish + grain + 0.1318 * deepTex, 0.0, 1.5);
    float gpos = clamp(pattern * 0.7310 + rim * 0.1411, 0.0, 1.0);
    vec3 rgb = gradient3(deepStop, baseCol, hotStop, gpos);
    float midCover = clamp(0.9175 * mid + 0.6921 * rim, 0.0, 1.0);
    rgb = mix(deepCol, rgb, midCover);
    // [layer:tex:body] -- the sampled multi-scale detail also grades the
    // composited body (deep volume included). v7: the grade is pole-faded
    // and partly gated through the pattern, so the family signature stays
    // dominant over the tile texture and the caps keep their clean body.
    float texBody = 0.8034 + 0.4806 * texDetail;
    rgb *= mix(1.0, texBody, atlasPoleW * (0.5473 + 0.4527 * clamp(pattern, 0.0, 1.0)));
    rgb = satLift(rgb, 1.1514);
    // Hue-preserving soft-clip on the hot crests: brightness saturates
    // toward the palette's own bright tint (1 - exp(-k * hotStop * x)),
    // never toward additive white -- rich color instead of pastel.
    vec3 softHot = 1.0 - exp(-2.3853 * hotStop * (pattern + 0.35 * rim));
    rgb = mix(rgb, softHot, 0.3172 * smoothstep(0.55, 1.10, pattern));
    vec3 accent = accentPalette(0.8569 + pattern * 0.4379);
    rgb = mix(rgb, rgb * (0.55 + 0.9 * accent), 0.4138);
    // Two-band chromatic dispersion on the rim (thin-film-like), biased
    // to vertexColor.rgb: band 1 multiplies the wide glow into the
    // palette-driven rgb, band 2 pulls the thin hot line toward the (also
    // vertexColor-derived) hot stop. Both bounded -- the owner recolor
    // override stays authoritative on every rim style.
    vec3 rimDisp = 0.5 + 0.5 * cos(vec3(1.0, 0.8065, 0.6452) * (rim * 0.8993 + baseUV.y * 0.4961 + 0.3725) * 6.2831853);
    rgb = mix(rgb, rgb * (0.72 + 0.56 * rimDisp), clamp(rim, 0.0, 1.0) * 0.1727);
    vec3 lineDisp = 0.5 + 0.5 * cos(vec3(0.6452, 0.8065, 1.0) * (rimLine * 1.0028 + baseUV.y * 0.31 + 0.1003) * 6.2831853);
    rgb = mix(rgb, hotStop * (0.62 + 0.50 * lineDisp), clamp(rimLine, 0.0, 1.0) * 0.2388);
    // [layer:wash:high_luma]
    // v10 near-white wash guard: near-white/high-luma palettes (chrome,
    // crystal) still washed to white at the apex under the linear per-luma
    // guards, so a smoothstep factor cuts the specular add, the emissive
    // add/white-mix and the energy overlay much harder for bright palettes
    // ONLY, and darkens the low-pattern body so structure shows. Recolor-
    // safe: washHi derives from the live vertexColor luma, nothing baked.
    float baseLuma = dot(baseCol, vec3(0.299, 0.587, 0.114));
    float washHi = smoothstep(0.55, 0.85, baseLuma);
    // uniform pre-clip compression + extra darkening of the low-pattern
    // body: near-white crests otherwise all clip to 1.0 and flatten into
    // one white sheet at the apex.
    rgb *= (1.0 - 0.2978 * washHi) * (1.0 - 0.2731 * washHi * (1.0 - clamp(pattern, 0.0, 1.0)));
    // [layer:light:wrapkey]
    // v8 fake lighting: wrap-diffuse + specular from a FIXED world key
    // light against the bumped normal, applied to the ENERGY only (the
    // refracted scene below is already lit). Recolor-safe: the diffuse is
    // a bounded multiplicative grade and the specular adds the palette's
    // own luma-capped hot stop -- no baked hue anywhere.
    vec3 keyL = vec3(-0.6266, 0.7777, 0.0506);
    float keyDiff = clamp((dot(bumpN, keyL) + 0.4335) / 1.4335, 0.0, 1.0);
    rgb *= 0.6723 + 0.6111 * keyDiff * (1.0 - 0.4652 * washHi);
    float keySpec = pow(clamp(dot(reflect(-viewV, bumpN), keyL), 0.0, 1.0), 14.8691);
    rgb += hotStop * (keySpec * 0.3284 * (1.0 - 0.6003 * washHi));
    // [layer:glass:beer]
    // W6/1.21.1 glass composite: no scene copy on this target, so the
    // real world shows through the TRANSLUCENT blend (see the glass
    // alpha floor below) instead of a refracted scene sample. What
    // survives from the 26.2 refraction layer is the Beer-Lambert
    // chord absorption -- the glass base color is the live palette
    // absorbed along the view path through the shell, so grazing
    // paths tint deeper and stay in-hue (recolor-safe) -- and the
    // energy weight, which still balances the family's pattern
    // against the see-through glass base: gaps read as tinted glass
    // over the alpha-blended world, features as energy, edges glow.
    vec3 glassCol = baseCol * exp(-0.4085 * chordN * (1.0 - baseCol));
    glassCol *= mix(vec3(1.0), baseCol, 0.3071);
    float energyW = clamp(0.2330 + 0.3954 * clamp(pattern, 0.0, 1.0) + 0.2659 * fresnel, 0.0, 0.8105);
    // v10 wash guard on the overlay: white palettes show MORE glass
    // (and world) instead of piling white energy on white glass.
    energyW *= 1.0 - 0.3407 * washHi;
    rgb = mix(glassCol, rgb, energyW);
    rgb += fresnel * hotStop * (1.1230 * (1.0 - 0.6368 * washHi));
    // v9 motif add: the per-id moving bright element rides ON TOP of the
    // energy-glass composite so the fingerprint stays identifiable.
    // Recolor-safe: its color is a hotStop/secCol mix, both live-derived
    // from vertexColor; its envelope is <= 2 Hz and day-quantized.
    rgb += motifGlow * mix(hotStop, secCol, 0.4344) * 0.9313;
    // [layer:emit:atlas_a]
    // Emissive glow: atlas.a is an EMISSION mask (never transparency) --
    // filament cores / cell edges / cracks / sparkles ADD a bright, hue-
    // preserving tint of the live palette. v7 wash guard: both the white-
    // mix and the emissive gain fall off with the palette's own luma, so
    // bright palettes (chrome/pastel) glow IN HUE instead of blowing to
    // white, while dark palettes keep their full glow. Scaled by the
    // family's own highlights and a slow day-quantized breath -- the glow
    // is spatial and strobe-free by construction.
    // (baseLuma/washHi were computed in the v10 wash-guard layer above;
    // washHi additionally cuts the white-mix AND the emissive add for
    // near-white palettes -- they glow in hue, never toward white.)
    vec3 emitCol = clamp(mix(baseCol, vec3(1.0), 0.2778 * max(0.0, 1.0 - 0.5570 * baseLuma - 0.5665 * washHi)), 0.0, 1.0);
    float emit = atlas.a * (0.3096 + 0.7169 * clamp(pattern, 0.0, 1.0)) * (1.0 - 0.0846 * (0.5 + 0.5 * sin(time * 0.125664))) * atlasPoleW;
    rgb += emit * 0.6636 * (1.0 - 0.7301 * baseLuma) * (1.0 - 0.5989 * washHi) * emitCol;
    // [layer:wash:knee]
    // v10 washHi-gated soft-knee: for near-white palettes every additive
    // path (fresnel glow, motif, emission, specular) lands >= 1.0 and CLIPS,
    // flattening the apex into one white sheet -- compress the overshoot
    // exponentially instead so crest/gap structure survives up to white.
    // Identity for dark palettes (washHi = 0 -> knee = 1.0).
    float washKnee = 1.0 - 0.2598 * washHi;
    vec3 washOver = max(rgb - vec3(washKnee), vec3(0.0));
    rgb = min(rgb, vec3(washKnee)) + (1.0 - washKnee) * (1.0 - exp(-washOver * 4.1495));
    // Presence BODY alpha (family-tuned, v6 solidity lift): a firm membrane
    // base even between features, a solid floor wherever the pattern is
    // present, rising toward the ceiling on bright features, plus the deep
    // volume's Beer-Lambert opacity and the emissive glow. v7 dissolve
    // authority: EVERY alpha modifier (emission, back-face densify, ghost
    // thinning, dither) acts on this body value, which is clamped to the
    // family ceiling and only THEN multiplied by vertexColor.a -- the
    // whitelisted-player dissolve is always the final, outermost factor.
    float presence = smoothstep(0.02, 0.30, pattern);
    float bodyAlpha = 0.3506 + 0.2727 * presence + 0.5233 * pattern + 0.1118 * (1.0 - deepTrans) + 0.1954 * emit;
    // v9: the motif also firms the membrane locally (pre-clamp, pre-
    // dissolve -- vertexColor.a still always wins).
    bodyAlpha += motifGlow * 0.1634;
    // [layer:inner:scaffold]
    // v11 far-shell interior: with the mesh's inward winding and cull OFF,
    // gl_FrontFacing is TRUE exactly where the camera sees the concave side
    // (the far shell from outside, the whole wall from inside).
    float innerFace = gl_FrontFacing ? 1.0 : 0.0;
    // INNER_SCAFFOLD: the R (coarse structure) channel of the two
    // slope-parallax paratex taps builds the interior lattice (the
    // taps already shift with the view: structural parallax for free).
    float innerScaf = clamp(0.5 * (deepTexA.r + deepTexB.r) * 1.1950 + hgtC * 0.3750, 0.0, 1.0);
    // geo/tech group: a 2x-coarser GHOST of this id's motif is etched
    // into the scaffold (the pow widens the Gaussian/band footprint
    // to roughly twice the surface motif's size)
    innerScaf = clamp(innerScaf + 0.3707 * pow(clamp(motifM, 0.0, 1.0), 0.25), 0.0, 1.0);
    vec3 innerCol = mix(deepStop, secCol, innerScaf);
    rgb = mix(rgb, innerCol, innerFace * 0.2410);
    bodyAlpha *= 1.0 + innerFace * 0.1894;
    // [layer:alpha:glassfloor]
    // W6/1.21.1 glass alpha floor, folded into bodyAlpha BEFORE the
    // ceiling clamp: the 26.2 near-opaque refraction floor becomes a
    // TRANSLUCENT floor -- the world behind the membrane is revealed by
    // the alpha blend now, so the gaps must stay genuinely see-through.
    // (No depth-soft fade either: that needed the scene depth copy.)
    bodyAlpha = max(bodyAlpha, 0.3770);
    // dissolve authority: clamp the body to the family ceiling FIRST, then
    // apply the whitelisted-player dissolve as the LAST alpha operation --
    // no path can push the final alpha above vertexColor.a * ceiling.
    float alpha = clamp(bodyAlpha, 0.0, 0.8496) * vertexColor.a;
    vec4 color = vec4(clamp(rgb, 0.0, 1.0), alpha);
    if (color.a < 0.01) {
        discard;
    }
    // vanilla 1.21.1 fog: linear_fog over the FogShape-picked distance
    // metric, exactly like the vanilla core shaders' fog_distance(pos,
    // FogShape) split across the two precomputed varyings.
    fragColor = linear_fog(color, FogShape == 0 ? sphericalVertexDistance : cylindricalVertexDistance, FogStart, FogEnd, FogColor);
}
