#version 150

#moj_import <fog.glsl>

// The shipped surface atlas (bubbleshield:textures/effect/surface_atlas.png,
// bound by ShieldPipelines' per-effect RenderType through its
// TextureStateShard): an 8x4 grid of 32 seamless grayscale tiles. Per texel:
// R = coarse structure, G = mid detail, B = fine grain, A = EMISSION mask
// (glow, NOT transparency). All hue comes from vertexColor at runtime
// (recolor-safe).
uniform sampler2D Sampler0;
// Vanilla auto-filled uniforms (declared in fx_NNN.json; ShaderInstance
// .setDefaultUniforms fills them every draw). GameTime spans one day cycle
// in [0, 1); FogShape picks the vanilla fog metric (0 = spherical).
uniform float GameTime;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;
uniform int FogShape;

// Bubble surface shader fx_644 -- family ORBITTRAP
// stack: deep=voro x3 taps | mid=orbittrap+curl+scroll | rim=graze_sparkle | flourish=echo | tex=nebula | motif=sigilx1+doublepulse
// fbm: standard x4 octaves | seed 7a2a3bcc1218619a
// v12 realism (1.21.1): glass tint 0.4037+Beer 0.6657*chord | energy 0.3788+0.4182*p | flow 0.095833 c/s | floor 0.3330
// GENERATED by tools/gen_surface_shaders.py -- do not hand-edit; edit the
// generator and regenerate instead (byte-stable, fixed seed).

in vec2 texCoord0;
in vec4 vertexColor;
in float sphericalVertexDistance;
in float cylindricalVertexDistance;
// Camera-relative world-space position from surface.vsh: the camera is
// the origin of this space, so view direction = -normalize(worldPos).
in vec3 worldPos;

out vec4 fragColor;

// 1 - smoothstep with ASCENDING edges. Replaces every reversed-edge
// smoothstep(hi, lo, x) call: edge0 >= edge1 is undefined by the GLSL
// spec; this form is numerically identical on conforming drivers.
float invsmooth(float lo, float hi, float x) {
    return 1.0 - smoothstep(lo, hi, x);
}

// Rodrigues rotation matrix around a baked unit axis. Driven with an
// angle that completes an INTEGER number of turns per day, the daily
// time wrap 1200 -> 0 lands exactly on a full turn -- the catalogue's
// first true (non-shear) rotation animation, only legal on the 3D
// sphere-direction domain (a 2D UV rotation would break the u wrap).
mat3 rotA(vec3 axis, float a) {
    float s = sin(a);
    float c = cos(a);
    float oc = 1.0 - c;
    return mat3(
        oc * axis.x * axis.x + c, oc * axis.x * axis.y + axis.z * s, oc * axis.z * axis.x - axis.y * s,
        oc * axis.x * axis.y - axis.z * s, oc * axis.y * axis.y + c, oc * axis.y * axis.z + axis.x * s,
        oc * axis.z * axis.x + axis.y * s, oc * axis.y * axis.z - axis.x * s, oc * axis.z * axis.z + c);
}

float hash21(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

vec2 hash22(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * vec3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.xx + p3.yz) * p3.zy);
}

vec3 hash33(vec3 p3) {
    p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yxz + 33.33);
    return fract((p3.xxy + p3.yxx) * p3.zyx);
}

// lattice-cell hash that tiles across the longitude seam: the cell's
// x id wraps every px cells, so u = 0 and u = 1 sample identical cells
float cellHash(vec2 cellId, float px) {
    return hash21(vec2(mod(cellId.x, px), cellId.y));
}

// value noise on a wrapping lattice (quintic fade): 'per' tiles the
// field so it is seamless across the u = 0/1 longitude wrap
float vnoise(vec2 p, vec2 per) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float a = hash21(mod(i, per));
    float b = hash21(mod(i + vec2(1.0, 0.0), per));
    float cc = hash21(mod(i + vec2(0.0, 1.0), per));
    float d = hash21(mod(i + vec2(1.0, 1.0), per));
    return mix(mix(a, b, u.x), mix(cc, d, u.x), u.y);
}

// divergence-free curl of a wrapping value-noise potential
vec2 curl2(vec2 p, vec2 per) {
    float e = 0.02;
    float n1 = vnoise(p + vec2(e, 0.0), per);
    float n2 = vnoise(p - vec2(e, 0.0), per);
    float n3 = vnoise(p + vec2(0.0, e), per);
    float n4 = vnoise(p - vec2(0.0, e), per);
    return vec2(n3 - n4, -(n1 - n2)) / (2.0 * e);
}

// 3D voronoi F1 + cell hash on the sphere-direction domain (seam- and
// pole-free, so no lattice wrap); 27 cells, const-bounded
vec2 voro3(vec3 p, float t) {
    vec3 n = floor(p);
    vec3 f = fract(p);
    float md = 8.0;
    float mh = 0.0;
    for (int k = -1; k <= 1; k++) {
        for (int j = -1; j <= 1; j++) {
            for (int i = -1; i <= 1; i++) {
                vec3 g = vec3(float(i), float(j), float(k));
                vec3 oh = hash33(n + g);
                vec3 o = 0.5 + 0.2922 * sin(t + 6.2831853 * oh);
                vec3 r = g + o - f;
                float d = dot(r, r);
                if (d < md) {
                    md = d;
                    mh = oh.x;
                }
            }
        }
    }
    return vec2(sqrt(md), mh);
}

// iq cosine palette, baked per effect; used ONLY for bounded accents
vec3 accentPalette(float t) {
    return vec3(0.5) + vec3(0.5) * cos(6.2831853 * (vec3(1.1999, 1.1445, 1.1902) * t
        + vec3(0.3411, 0.2247, 0.3314)));
}

// 3-stop shadow/body/highlight grade (two smoothstep segments): every
// stop is derived from vertexColor.rgb at RUNTIME, so the owner /color
// override recolors shadow, body and highlight together (recolor-safe
// by construction).
vec3 gradient3(vec3 deepStop, vec3 body, vec3 hotStop, float x) {
    vec3 g = mix(deepStop, body, smoothstep(0.0, 0.5656, x));
    return mix(g, hotStop, smoothstep(0.5656, 1.0, x));
}

// saturation lift: mixes AWAY from luma (s > 1), deepening the chroma
// without changing the hue -- the anti-washout pass
vec3 satLift(vec3 col, float s) {
    float l = dot(col, vec3(0.299, 0.587, 0.114));
    return clamp(mix(vec3(l), col, s), 0.0, 1.0);
}

// Rodrigues rotation of the color vector around the grey axis; nudges
// the highlight stop's hue away from the body color. The input is
// always derived from vertexColor.rgb at runtime, so recolor-safe.
vec3 hueSpin(vec3 col, float a) {
    const vec3 k = vec3(0.57735027);
    float ca = cos(a);
    float sa = sin(a);
    return col * ca + cross(k, col) * sa + k * dot(k, col) * (1.0 - ca);
}

// silhouette estimator: the camera-distance varying changes fastest per
// pixel at grazing angles, so fwidth() peaks at the bubble's rim.
// Normalizing by the distance itself keeps the rim width roughly
// view-consistent near and far.
float rimGraze() {
    float g = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    return smoothstep(0.0062, 0.0462, g);
}

// hash-cell twinkle: sparse offset star points with per-cell phase;
// cells wrap every px in x so the field tiles the u seam. The per-
// cell rate is an INTEGER number of cycles per day (the hash picks
// the integer and offsets the phase), so the daily time wrap
// 1200 -> 0 lands exactly on a whole cycle -- no twinkle snap.
float sparkle(vec2 p, float t, float px) {
    vec2 cellId = floor(p);
    vec2 f = fract(p) - 0.5;
    float h = cellHash(cellId, px);
    vec2 off = vec2(cellHash(cellId + 11.3, px), cellHash(cellId + 27.9, px)) - 0.5;
    float d = length(f - off * 0.55);
    float turns = 382.0 + floor(h * 955.0);
    float tw = pow(0.5 + 0.5 * sin(t * turns * (6.2831853 / 1200.0) + h * 39.0), 6.0);
    return step(0.6944, h) * invsmooth(0.02, 0.22, d) * tw;
}

// GameTime-phased expanding rings from hash-seeded surface points; the
// chordal x-distance (sin of the longitude difference) keeps the rings
// round across the u = 0/1 seam, and the phase speed is day-quantized
float ringPulse(vec2 uv, float t) {
    float acc = 0.0;
    for (int i = 0; i < 3; i++) {
        float fi = float(i);
        vec2 c = hash22(vec2(fi * 7.31 + 34.1349, fi * 2.97));
        float phase = fract(t * 0.137500 + fi * 0.37);
        float d = length(vec2(sin((uv.x - c.x) * 3.1415927) * 0.3183, uv.y - c.y));
        acc += invsmooth(0.0, 0.05, abs(d - phase * 0.7)) * (1.0 - phase);
    }
    return acc;
}

// one inset-clamped tap of this file's surface-atlas tile: fract()
// wraps the (seam-periodic) repeat domain, and the inset keeps the
// linear-filtered lookup inside the tile for ANY flow/gradient offset
// (8x4 tile grid -> per-axis scale vec2(0.125, 0.25))
vec4 atlasTile(vec2 p) {
    return texture(Sampler0, (vec2(7.0000, 1.0000) + clamp(fract(p), 0.004, 0.996)) * vec2(0.125, 0.25));
}

// DEEP-layer field (3D voronoi blob volume), sampled on the 3D sphere direction by
// the correlated parallax planes -- seam- and pole-free
float deepField(vec3 p, float t) {
    vec2 v = voro3(p, t * 0.591667);
    return invsmooth(0.15, 0.95, v.x);
}

void main() {
    // GameTime spans one day cycle in [0, 1); scale to roughly seconds.
    // All constant speeds below are day-quantized (integer cycles or
    // integer lattice periods per day) so the daily wrap does not pop.
    float time = GameTime * 1200.0;
    // texCoord0 is the raw sphere UV, already in [0,1]; fract() is only a
    // defensive wrap. Seam-freedom in u comes from the wrapping-lattice /
    // periodic-domain sampling below, NOT from this fract().
    vec2 baseUV = fract(texCoord0);
    vec2 midPer = vec2(3.0000, 5.0000);
    // 3D sphere direction reconstructed from the UV (u -> longitude,
    // v -> latitude): any field sampled on it is periodic across the
    // u = 0/1 seam AND uniform at the poles by construction.
    vec3 sdir = vec3(sin(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        cos(3.1415927 * baseUV.y),
        sin(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    // v11: the view direction is hoisted up here (the thickness and
    // parallax layers need it before the normal block) together with
    // its component TANGENT to the shell surface: Vt is the true
    // parallax direction -- zero head-on, maximal at the grazing limb,
    // seam-safe by construction (pure 3D geometry, no UV involved).
    vec3 viewV = -normalize(worldPos);
    vec3 Vt = viewV - dot(viewV, sdir) * sdir;

    // [palette:gradient3]
    // Runtime 3-stop palette derived from vertexColor.rgb: the dark stop
    // darkens AND saturates (base*base stays in-hue instead of greying);
    // the hot stop is a LUMA-CAPPED CHROMATIC highlight -- a hue-nudged,
    // saturation-lifted, brightened base whose luma is capped relative to
    // the base luma, so the highlight can NEVER wash out toward white.
    // The owner /color override replaces vertexColor wholesale, so the
    // whole ramp re-derives from it -- recolor-safe by construction.
    vec3 baseCol = vertexColor.rgb;
    vec3 deepStop = baseCol * baseCol * 0.6336;
    vec3 spun = clamp(hueSpin(baseCol, -0.2810), 0.0, 1.0);
    vec3 hotStop = satLift(spun, 1.2506) * 1.45;
    float hotLuma = dot(hotStop, vec3(0.299, 0.587, 0.114));
    float lumaCap = max(0.5304, dot(baseCol, vec3(0.299, 0.587, 0.114)) * 1.6708);
    hotStop = clamp(hotStop * min(1.0, lumaCap / max(hotLuma, 0.001)), 0.0, 1.0);
    // Secondary palette color, derived IN-SHADER from vertexColor via the
    // baked primary->secondary relation (hue angle + sat/value ratios) --
    // the vertex format has no second color attribute, and deriving both
    // from the live vertexColor keeps the owner recolor authoritative.
    vec3 secCol = clamp(satLift(clamp(hueSpin(baseCol, 0.4174), 0.0, 1.0), 1.1301) * 0.4183, 0.0, 1.0);

    // [layer:deep:parallax3d_voro_x3]
    // Interior volume: correlated parallax PLANES of ONE deep field on
    // the 3D sphere direction, composited FRONT-TO-BACK under Beer-
    // Lambert transmittance -- each plane occludes the ones behind it,
    // and its light lands in BOTH the color accumulator (per-plane color
    // receding baseCol -> secCol -> dark stop) and the opacity term that
    // feeds the alpha. Farther planes show finer features, spin slower
    // (integer turns/day: the daily wrap lands on a full turn) and slide
    // along the TRUE view-tangent parallax direction (v11: par = Vt *
    // parScale replaces the old screen-space rimDir estimate -- planes
    // hold still head-on and shear apart toward the grazing limb).
    vec3 spinAxis = vec3(0.3632, -0.9309, 0.0400);
    vec3 par = Vt * 2.2410;
    // v11 breathing: the deep domain slowly in/exhales (day-quantized,
    // well under 2 Hz) so the interior volume reads alive, not baked.
    float deepBreath = 1.0 + 0.0161 * sin(time * 1.314233);
    float deepTrans = 1.0;
    vec3 deepCol = vec3(0.0);
    float dp = deepField(rotA(spinAxis, time * 0.073304) * (sdir * (2.6340 * deepBreath)), time);
    deepCol += deepTrans * dp * baseCol;
    deepTrans *= 1.0 - 0.4879 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.068068) * (sdir * (3.4410 * deepBreath)) + par * 0.0357, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 0.4941), deepStop, 0.1812);
    deepTrans *= 1.0 - 0.4879 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.062832) * (sdir * (4.2480 * deepBreath)) + par * 0.0715, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 0.9882), deepStop, 0.3623);
    deepTrans *= 1.0 - 0.4879 * clamp(dp, 0.0, 1.0);
    deepCol *= 0.8395;
    float deepPat = pow(clamp((1.0 - deepTrans) * 1.1551, 0.0, 1.0), 1.2306);

    // [layer:mid:orbittrap_curl_scroll]
    // Signature structure of this effect, domain-warped and animated.
    // This family's signature field also lives on the sphere direction
    // (seam- and pole-free) and TRULY rotates, day-safely.
    vec3 mdir = rotA(spinAxis, time * 0.026180) * (sdir * 0.8882);
    vec2 auv = vec2(baseUV.x * 3.0000, baseUV.y * 3.0000) + vec2(0.222500, 0.104167) * time;
    vec2 wuv = auv + 0.1987 * curl2(auv + vec2(0.0, time * 0.070833), midPer);
    vec2 otZ = mdir.xy * 1.2163 + vec2(mdir.z * 0.3143, 0.0);
    vec2 otC = vec2(-0.8007, 0.6433) + 0.0448 * vec2(sin(time * 0.031416), cos(time * 0.020944));
    float otPt = 100.0;
    float otLn = 100.0;
    for (int i = 0; i < 7; i++) {
        otZ = vec2(otZ.x * otZ.x - otZ.y * otZ.y, 2.0 * otZ.x * otZ.y) + otC;
        otZ = clamp(otZ, -8.0, 8.0);
        otPt = min(otPt, length(otZ - vec2(-0.1457, -0.1515)));
        otLn = min(otLn, abs(otZ.y - otZ.x * -0.4933));
    }
    float otGlow = pow(clamp(1.0 - otPt * 0.7805, 0.0, 1.0), 3.3791);
    float otWire = pow(clamp(1.0 - otLn * 1.9736, 0.0, 1.0), 4.6485);
    float otBand = 0.5 + 0.5 * sin(otPt * 8.4196 - time * 0.670206);
    float mid = clamp(otGlow * (0.55 + 0.45 * otBand) + otWire * 0.6, 0.0, 1.25);

    // [layer:tex:nebula]
    // Real sampled detail from atlas tile 15 (nebula), matched to this
    // family's technique. The INTEGER repeat multiplier keeps the lookup exact
    // across the u = 0/1 wrap (the domain spans an integer lattice period per
    // wrap, and its drifts shift integer periods per day -- day-wrap-safe);
    // the inset clamp keeps the linear-filtered sample inside this tile.
    // v9 family texture-drift: a baked per-FAMILY drift vector (direction
    // golden-angle-spread by family index, speed day-quantized against the
    // tile period) -- two families sharing a tile move it differently.
    vec2 texUV = wuv * 5.0000 + vec2(0.015833, -0.060833) * time;
    // v8 height taps: the atlas R/G/B structural mix doubles as a HEIGHT
    // field. Its 2-tap gradient (a) tilts the shading normal (bump) and
    // (b) builds the divergence-free flow vector the energy crawls along.
    vec3 hgtW = vec3(0.4135, 0.3331, 0.2534);
    float hgtC = dot(atlasTile(texUV).rgb, hgtW);
    float hgtX = dot(atlasTile(texUV + vec2(0.0207, 0.0)).rgb, hgtW);
    float hgtY = dot(atlasTile(texUV + vec2(0.0, 0.0207)).rgb, hgtW);
    vec2 atlasSlope = vec2(hgtX - hgtC, hgtY - hgtC);
    // [layer:flow:atlas_curl]
    // v8 dual-phase flow-map advection: two taps advected along the curl
    // of the height field at half-cycle-offset fract phases, crossfaded
    // by phase distance -- the energy visibly CRAWLS across the membrane.
    // The phase speed completes integer cycles per day (day-wrap-safe)
    // and the flow vector is a function of the seam-periodic texUV domain
    // (u = 0/1 safe by construction).
    vec2 flowVec = vec2(atlasSlope.y, -atlasSlope.x) * 1.7631;
    float flowA = fract(time * 0.095833);
    float flowB = fract(flowA + 0.5);
    vec4 atlas = mix(atlasTile(texUV + flowVec * flowA), atlasTile(texUV + flowVec * flowB), abs(flowA - 0.5) * 2.0);
    // v7 atlas pole fade: texUV is longitude-dependent, so at v = 0/1 the
    // tile would pinch into an apex rosette. Every atlas INFLUENCE (mid
    // lift, body grade, emission) fades to its no-atlas value at the caps.
    float atlasPoleW = smoothstep(0.02, 0.12, min(baseUV.y, 1.0 - baseUV.y));
    float texDetail = clamp(atlas.r * 0.4053 + atlas.g * 0.3265 + atlas.b * 0.2483, 0.0, 1.0);
    // the multi-scale texture layers modulate the signature and add a lift
    // that is mostly GATED through the family's own pattern (v7) -- the
    // signature stays dominant and dark palettes keep their dark gaps
    mid = clamp(mid * mix(1.0, 0.6200 + 0.7412 * texDetail, atlasPoleW) + 0.1226 * texDetail * (0.2678 + 0.7322 * clamp(mid, 0.0, 1.0)) * atlasPoleW, 0.0, 1.5);

    // [layer:normal:atlas_bump]
    // v8 perturbed shading normal: the atlas height gradient tilts the
    // analytic sphere normal along its tangent frame (dsdir/du, dsdir/dv).
    // Pole-faded: the u tangent degenerates at the caps, so the bump
    // scales with atlasPoleW and the normal falls back to sdir there.
    vec3 tanU = vec3(-sin(6.2831853 * baseUV.x), 0.0, cos(6.2831853 * baseUV.x));
    vec3 tanV = vec3(cos(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        -sin(3.1415927 * baseUV.y),
        cos(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    vec3 bumpN = normalize(sdir + (tanU * atlasSlope.x + tanV * atlasSlope.y) * (1.1860 * atlasPoleW));
    // fresnel rim (view angle against the bumped normal; viewV was
    // hoisted next to sdir in v11): the classic force-field edge glow;
    // abs() keeps the back faces consistent
    float fresnel = pow(1.0 - abs(dot(bumpN, viewV)), 3.0730);

    // [layer:thick:paratex]
    // v11 in-shell texture parallax: two EXTRA atlas taps stepped along
    // the view tangent projected onto the tangent frame (VtUV) sample
    // the tile as if suspended deeper INSIDE the glass -- the detail
    // visibly shifts against the surface as the view moves. Seam/day-
    // safe: the offset lives on the periodic texUV domain.
    vec2 VtUV = vec2(dot(Vt, tanU), dot(Vt, tanV));
    vec3 deepTexA = atlasTile(texUV + VtUV * 0.0824).rgb;
    vec3 deepTexB = atlasTile(texUV - VtUV * 0.0824).rgb;
    float deepTex = 0.5 * (dot(deepTexA, hgtW) + dot(deepTexB, hgtW));

    // [layer:thick:chord]
    // v11 volumetric thickness: the membrane is a shell of relative
    // thickness rho = 0.1616 (celestial material group) on the unit
    // sphere. chord = the view ray's path length through the shell,
    // normalized by the radial thickness and limb-clamped: chordN is
    // 1.0 head-on and saturates at 3.0 toward the grazing silhouette.
    // Two-case: while the ray still hits the inner sphere the path is
    // cosV - sqrt(disc); past the tangent ring it misses and runs the
    // full outer chord 2*cosV, capped at the inner-tangent maximum
    // 2*sqrt(1 - (1-rho)^2) = 1.0901.
    float cosV = abs(dot(sdir, viewV));
    float chordDisc = 0.8384 * 0.8384 - (1.0 - cosV * cosV);
    float chord = chordDisc > 0.0 ? cosV - sqrt(chordDisc) : min(2.0 * cosV, 1.0901);
    float chordN = min(chord / 0.1616, 3.0);

    // [layer:rim:graze_sparkle]
    // Silhouette / band lift so the membrane reads as a curved shell:
    // a wide soft inner glow (style-specific) plus a thin hot line at
    // the very edge. The slope is normalized by the camera distance so
    // the rim width stays view-consistent near and far.
    float rimSlope = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    float rimLine = smoothstep(0.0625, 0.0916, rimSlope);
    float rimGlint = sparkle(baseUV * 11.0000, time, 11.0000);
    float rim = rimGraze() * 0.8046 * (0.7 + 0.6 * rimGlint) + 0.5096 * rimGlint;
    // v8: the fresnel term folds into the rim glow -- edges glow, the
    // center stays refraction-dominated (see the [layer:refract] mix).
    rim = clamp(rim + 0.7460 * rimLine + 0.5690 * fresnel, 0.0, 1.4);

    // Flourish accent + micro grain keep large areas alive up close.
    float flourish = 0.1684 * ringPulse(baseUV + vec2(0.13, 0.31), time);
    float grain = 0.0577 * (cellHash(floor(wuv * 48.0000) + vec2(floor(time * 2.0), 0.0), 144.0000) - 0.5);

    // [layer:motif:sigil:doublepulse]
    // v9 per-id motif fingerprint: this effect's unique moving bright
    // element (sigil x1) under its doublepulse emissive envelope.
    float motifP = fract(time * 0.355000 + 0.8791);
    float motifEnv = 0.52 + 0.75 * exp(-140.0 * (motifP - 0.16) * (motifP - 0.16)) + 0.60 * exp(-140.0 * (motifP - 0.38) * (motifP - 0.38));
    float motifA = baseUV.x * 3.0000 + -1.0 * time * 0.060833 + 0.4498;
    float motifSig = pow(0.5 + 0.5 * cos(6.2831853 * motifA), 14.7446);
    float motifDy = (baseUV.y - 0.4686) * 11.8241;
    float motifBand = exp(-motifDy * motifDy);
    float motifM = motifSig * motifBand;
    float motifGlow = clamp(motifM, 0.0, 1.2) * motifEnv;

    // Recolor-safe composite v4: the whole pattern is graded through the
    // vertexColor-derived 3-stop ramp (low pattern falls to the DARK stop
    // and low alpha -- never pale grey), the deep volume sits BEHIND the
    // signature structure, and the gradient position leans toward the hot
    // stop at the rim (chromatic rim). The vertexColor.a dissolve near
    // whitelisted players always wins the final alpha.
    // [layer:v5:slopeparallax]
    // v5 slope-parallax multi-tap: three EXTRA taps of the deep field,
    // stepped along the silhouette slope (par, screen-space: seam-safe)
    // at growing offset and scale -- the membrane texture itself gains
    // depth where the shell curves away from the view.
    float v5Par = deepField(sdir * 2.1016 + par * 0.0602, time) * 0.5;
    v5Par += deepField(sdir * 2.8372 + par * 0.1204, time) * 0.3;
    v5Par += deepField(sdir * 3.6778 + par * 0.1806, time) * 0.2;
    float pattern = clamp(0.1545 * deepPat * mix(1.0, chordN, 0.2141) + 0.9554 * mid + 0.8013 * rim + flourish + grain + 0.1577 * v5Par + 0.2354 * deepTex, 0.0, 1.5);
    float gpos = clamp(pattern * 0.8745 + rim * 0.2255, 0.0, 1.0);
    vec3 rgb = gradient3(deepStop, baseCol, hotStop, gpos);
    float midCover = clamp(1.0214 * mid + 0.4352 * rim, 0.0, 1.0);
    rgb = mix(deepCol, rgb, midCover);
    // [layer:tex:body] -- the sampled multi-scale detail also grades the
    // composited body (deep volume included). v7: the grade is pole-faded
    // and partly gated through the pattern, so the family signature stays
    // dominant over the tile texture and the caps keep their clean body.
    float texBody = 0.7992 + 0.4908 * texDetail;
    rgb *= mix(1.0, texBody, atlasPoleW * (0.4627 + 0.5373 * clamp(pattern, 0.0, 1.0)));
    rgb = satLift(rgb, 1.3120);
    // Hue-preserving soft-clip on the hot crests: brightness saturates
    // toward the palette's own bright tint (1 - exp(-k * hotStop * x)),
    // never toward additive white -- rich color instead of pastel.
    vec3 softHot = 1.0 - exp(-3.3940 * hotStop * (pattern + 0.35 * rim));
    rgb = mix(rgb, softHot, 0.3539 * smoothstep(0.55, 1.10, pattern));
    vec3 accent = accentPalette(0.6607 + pattern * 0.5954);
    rgb = mix(rgb, rgb * (0.55 + 0.9 * accent), 0.2396);
    // Two-band chromatic dispersion on the rim (thin-film-like), biased
    // to vertexColor.rgb: band 1 multiplies the wide glow into the
    // palette-driven rgb, band 2 pulls the thin hot line toward the (also
    // vertexColor-derived) hot stop. Both bounded -- the owner recolor
    // override stays authoritative on every rim style.
    vec3 rimDisp = 0.5 + 0.5 * cos(vec3(1.0, 0.8065, 0.6452) * (rim * 0.7059 + baseUV.y * 0.3686 + 0.0302) * 6.2831853);
    rgb = mix(rgb, rgb * (0.72 + 0.56 * rimDisp), clamp(rim, 0.0, 1.0) * 0.2090);
    vec3 lineDisp = 0.5 + 0.5 * cos(vec3(0.6452, 0.8065, 1.0) * (rimLine * 1.0407 + baseUV.y * 0.31 + 0.3438) * 6.2831853);
    rgb = mix(rgb, hotStop * (0.62 + 0.50 * lineDisp), clamp(rimLine, 0.0, 1.0) * 0.1999);
    // [layer:wash:high_luma]
    // v10 near-white wash guard: near-white/high-luma palettes (chrome,
    // crystal) still washed to white at the apex under the linear per-luma
    // guards, so a smoothstep factor cuts the specular add, the emissive
    // add/white-mix and the energy overlay much harder for bright palettes
    // ONLY, and darkens the low-pattern body so structure shows. Recolor-
    // safe: washHi derives from the live vertexColor luma, nothing baked.
    float baseLuma = dot(baseCol, vec3(0.299, 0.587, 0.114));
    float washHi = smoothstep(0.55, 0.85, baseLuma);
    // uniform pre-clip compression + extra darkening of the low-pattern
    // body: near-white crests otherwise all clip to 1.0 and flatten into
    // one white sheet at the apex.
    rgb *= (1.0 - 0.3519 * washHi) * (1.0 - 0.3501 * washHi * (1.0 - clamp(pattern, 0.0, 1.0)));
    // [layer:light:wrapkey]
    // v8 fake lighting: wrap-diffuse + specular from a FIXED world key
    // light against the bumped normal, applied to the ENERGY only (the
    // refracted scene below is already lit). Recolor-safe: the diffuse is
    // a bounded multiplicative grade and the specular adds the palette's
    // own luma-capped hot stop -- no baked hue anywhere.
    vec3 keyL = vec3(-0.6497, 0.5659, 0.5076);
    float keyDiff = clamp((dot(bumpN, keyL) + 0.4825) / 1.4825, 0.0, 1.0);
    rgb *= 0.6383 + 0.4188 * keyDiff * (1.0 - 0.5590 * washHi);
    float keySpec = pow(clamp(dot(reflect(-viewV, bumpN), keyL), 0.0, 1.0), 19.1041);
    rgb += hotStop * (keySpec * 0.3014 * (1.0 - 0.5628 * washHi));
    // [layer:glass:beer]
    // W6/1.21.1 glass composite: no scene copy on this target, so the
    // real world shows through the TRANSLUCENT blend (see the glass
    // alpha floor below) instead of a refracted scene sample. What
    // survives from the 26.2 refraction layer is the Beer-Lambert
    // chord absorption -- the glass base color is the live palette
    // absorbed along the view path through the shell, so grazing
    // paths tint deeper and stay in-hue (recolor-safe) -- and the
    // energy weight, which still balances the family's pattern
    // against the see-through glass base: gaps read as tinted glass
    // over the alpha-blended world, features as energy, edges glow.
    vec3 glassCol = baseCol * exp(-0.6657 * chordN * (1.0 - baseCol));
    glassCol *= mix(vec3(1.0), baseCol, 0.4037);
    float energyW = clamp(0.3788 + 0.4182 * clamp(pattern, 0.0, 1.0) + 0.1919 * fresnel, 0.0, 0.8644);
    // v10 wash guard on the overlay: white palettes show MORE glass
    // (and world) instead of piling white energy on white glass.
    energyW *= 1.0 - 0.2454 * washHi;
    rgb = mix(glassCol, rgb, energyW);
    rgb += fresnel * hotStop * (0.8903 * (1.0 - 0.6724 * washHi));
    // v9 motif add: the per-id moving bright element rides ON TOP of the
    // energy-glass composite so the fingerprint stays identifiable.
    // Recolor-safe: its color is a hotStop/secCol mix, both live-derived
    // from vertexColor; its envelope is <= 2 Hz and day-quantized.
    rgb += motifGlow * mix(hotStop, secCol, 0.3187) * 1.0465;
    // [layer:emit:atlas_a]
    // Emissive glow: atlas.a is an EMISSION mask (never transparency) --
    // filament cores / cell edges / cracks / sparkles ADD a bright, hue-
    // preserving tint of the live palette. v7 wash guard: both the white-
    // mix and the emissive gain fall off with the palette's own luma, so
    // bright palettes (chrome/pastel) glow IN HUE instead of blowing to
    // white, while dark palettes keep their full glow. Scaled by the
    // family's own highlights and a slow day-quantized breath -- the glow
    // is spatial and strobe-free by construction.
    // (baseLuma/washHi were computed in the v10 wash-guard layer above;
    // washHi additionally cuts the white-mix AND the emissive add for
    // near-white palettes -- they glow in hue, never toward white.)
    vec3 emitCol = clamp(mix(baseCol, vec3(1.0), 0.3519 * max(0.0, 1.0 - 0.5975 * baseLuma - 0.6940 * washHi)), 0.0, 1.0);
    float emit = atlas.a * (0.3067 + 0.6878 * clamp(pattern, 0.0, 1.0)) * (1.0 - 0.1443 * (0.5 + 0.5 * sin(time * 0.146608))) * atlasPoleW;
    rgb += emit * 0.7143 * (1.0 - 0.7585 * baseLuma) * (1.0 - 0.5047 * washHi) * emitCol;
    // [layer:v5:softknee]
    // v5 soft-knee highlight rolloff: channels over the knee compress
    // exponentially instead of clipping (continuous at the knee since
    // exp(0) = 1), so hot crests keep hue separation right up to white.
    vec3 v5Over = max(rgb - vec3(0.6665), vec3(0.0));
    rgb = min(rgb, vec3(0.6665)) + 0.3335 * (1.0 - exp(-v5Over * 1.7142));
    // [layer:wash:knee]
    // v10 washHi-gated soft-knee: for near-white palettes every additive
    // path (fresnel glow, motif, emission, specular) lands >= 1.0 and CLIPS,
    // flattening the apex into one white sheet -- compress the overshoot
    // exponentially instead so crest/gap structure survives up to white.
    // Identity for dark palettes (washHi = 0 -> knee = 1.0).
    float washKnee = 1.0 - 0.2282 * washHi;
    vec3 washOver = max(rgb - vec3(washKnee), vec3(0.0));
    rgb = min(rgb, vec3(washKnee)) + (1.0 - washKnee) * (1.0 - exp(-washOver * 3.1919));
    // Presence BODY alpha (family-tuned, v6 solidity lift): a firm membrane
    // base even between features, a solid floor wherever the pattern is
    // present, rising toward the ceiling on bright features, plus the deep
    // volume's Beer-Lambert opacity and the emissive glow. v7 dissolve
    // authority: EVERY alpha modifier (emission, back-face densify, ghost
    // thinning, dither) acts on this body value, which is clamped to the
    // family ceiling and only THEN multiplied by vertexColor.a -- the
    // whitelisted-player dissolve is always the final, outermost factor.
    float presence = smoothstep(0.02, 0.30, pattern);
    float bodyAlpha = 0.3555 + 0.2915 * presence + 0.5553 * pattern + 0.1345 * (1.0 - deepTrans) + 0.1514 * emit;
    // v9: the motif also firms the membrane locally (pre-clamp, pre-
    // dissolve -- vertexColor.a still always wins).
    bodyAlpha += motifGlow * 0.1871;
    // [layer:v5:backface]
    // v5 densify/dim (gl_FrontFacing is a builtin, no uniform needed).
    // Historical note: with the mesh's inward winding this condition is
    // TRUE on the CONVEX (near) face, not the far shell -- but every v5
    // family was tuned against exactly this look, so it stays on purpose
    // (the [layer:inner:*] block is the one keyed to the real far shell).
    float v5Back = gl_FrontFacing ? 0.0 : 1.0;
    rgb = mix(rgb, deepStop, v5Back * 0.2857);
    bodyAlpha *= 1.0 + v5Back * 0.2442;
    // [layer:v5:ghostalpha]
    // v5 luminance-weighted ghost translucency: dark areas thin out while
    // bright features hold. Multiplicative on the body alpha (pre-clamp,
    // pre-dissolve), so the vertexColor.a dissolve still always wins.
    float v5Luma = dot(clamp(rgb, 0.0, 1.0), vec3(0.299, 0.587, 0.114));
    bodyAlpha *= 0.7384 + 0.2616 * smoothstep(0.03, 0.42, v5Luma);
    // [layer:v5:dither]
    // v5 blue-noise-style alpha dither (interleaved gradient noise on
    // gl_FragCoord) breaks translucency banding; multiplicative on the
    // body alpha, so bodyAlpha = 0 stays exactly 0 and the ceiling clamp
    // below still bounds it.
    float v5Dither = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));
    bodyAlpha *= 1.0 + (v5Dither - 0.5) * 0.0764;
    // [layer:inner:stars]
    // v11 far-shell interior: with the mesh's inward winding and cull OFF,
    // gl_FrontFacing is TRUE exactly where the camera sees the concave side
    // (the far shell from outside, the whole wall from inside).
    float innerFace = gl_FrontFacing ? 1.0 : 0.0;
    // INNER_PARALLAX_STARS: the deep field re-sampled at plane-0 scale
    // on a SLOWED rotation (0.8x re-rounded turns) with a view-tangent
    // offset -- a star shell parallaxing behind the surface.
    float innerStar = deepField(rotA(spinAxis, time * 0.052360 + 3.4372) * (sdir * 2.6340) + Vt * 0.4741, time);
    float innerLit = pow(clamp(innerStar, 0.0, 1.0), 1.5630);
    vec3 innerCol = mix(deepStop, mix(secCol, hotStop, 0.5733), innerLit);
    rgb = mix(rgb, innerCol, innerFace * 0.3050);
    bodyAlpha *= 1.0 + innerFace * 0.1487;
    // [layer:alpha:glassfloor]
    // W6/1.21.1 glass alpha floor, folded into bodyAlpha BEFORE the
    // ceiling clamp: the 26.2 near-opaque refraction floor becomes a
    // TRANSLUCENT floor -- the world behind the membrane is revealed by
    // the alpha blend now, so the gaps must stay genuinely see-through.
    // (No depth-soft fade either: that needed the scene depth copy.)
    bodyAlpha = max(bodyAlpha, 0.3330);
    // dissolve authority: clamp the body to the family ceiling FIRST, then
    // apply the whitelisted-player dissolve as the LAST alpha operation --
    // no path can push the final alpha above vertexColor.a * ceiling.
    float alpha = clamp(bodyAlpha, 0.0, 0.8668) * vertexColor.a;
    vec4 color = vec4(clamp(rgb, 0.0, 1.0), alpha);
    if (color.a < 0.01) {
        discard;
    }
    // vanilla 1.21.1 fog: linear_fog over the FogShape-picked distance
    // metric, exactly like the vanilla core shaders' fog_distance(pos,
    // FogShape) split across the two precomputed varyings.
    fragColor = linear_fog(color, FogShape == 0 ? sphericalVertexDistance : cylindricalVertexDistance, FogStart, FogEnd, FogColor);
}
