#version 150

#moj_import <fog.glsl>

// The shipped surface atlas (bubbleshield:textures/effect/surface_atlas.png,
// bound by ShieldPipelines' per-effect RenderType through its
// TextureStateShard): an 8x4 grid of 32 seamless grayscale tiles. Per texel:
// R = coarse structure, G = mid detail, B = fine grain, A = EMISSION mask
// (glow, NOT transparency). All hue comes from vertexColor at runtime
// (recolor-safe).
uniform sampler2D Sampler0;
// Vanilla auto-filled uniforms (declared in fx_NNN.json; ShaderInstance
// .setDefaultUniforms fills them every draw). GameTime spans one day cycle
// in [0, 1); FogShape picks the vanilla fog metric (0 = spherical).
uniform float GameTime;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;
uniform int FogShape;

// Bubble surface shader fx_683 -- family HOLOPARALLAX
// stack: deep=fbm x3 taps | mid=holoparallax+curl+flicker | rim=lat | flourish=echo | tex=glyph_ring | motif=corex1+sparklegate
// fbm: ridged x5 octaves | seed 4364dd09dce72ceb
// v12 realism (1.21.1): glass tint 0.2004+Beer 0.3810*chord | energy 0.2528+0.4714*p | flow 0.082500 c/s | floor 0.3486
// GENERATED by tools/gen_surface_shaders.py -- do not hand-edit; edit the
// generator and regenerate instead (byte-stable, fixed seed).

in vec2 texCoord0;
in vec4 vertexColor;
in float sphericalVertexDistance;
in float cylindricalVertexDistance;
// Camera-relative world-space position from surface.vsh: the camera is
// the origin of this space, so view direction = -normalize(worldPos).
in vec3 worldPos;

out vec4 fragColor;

// 1 - smoothstep with ASCENDING edges. Replaces every reversed-edge
// smoothstep(hi, lo, x) call: edge0 >= edge1 is undefined by the GLSL
// spec; this form is numerically identical on conforming drivers.
float invsmooth(float lo, float hi, float x) {
    return 1.0 - smoothstep(lo, hi, x);
}

// Rodrigues rotation matrix around a baked unit axis. Driven with an
// angle that completes an INTEGER number of turns per day, the daily
// time wrap 1200 -> 0 lands exactly on a full turn -- the catalogue's
// first true (non-shear) rotation animation, only legal on the 3D
// sphere-direction domain (a 2D UV rotation would break the u wrap).
mat3 rotA(vec3 axis, float a) {
    float s = sin(a);
    float c = cos(a);
    float oc = 1.0 - c;
    return mat3(
        oc * axis.x * axis.x + c, oc * axis.x * axis.y + axis.z * s, oc * axis.z * axis.x - axis.y * s,
        oc * axis.x * axis.y - axis.z * s, oc * axis.y * axis.y + c, oc * axis.y * axis.z + axis.x * s,
        oc * axis.z * axis.x + axis.y * s, oc * axis.y * axis.z - axis.x * s, oc * axis.z * axis.z + c);
}

float hash21(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

vec2 hash22(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * vec3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.xx + p3.yz) * p3.zy);
}

// Hoskins-style 3D->1D hash; small multiplier keeps fp32 precision
// alive over the whole sphere-direction domain
float hash31(vec3 p3) {
    p3 = fract(p3 * 0.1031);
    p3 += dot(p3, p3.zyx + 31.32);
    return fract((p3.x + p3.y) * p3.z);
}

// lattice-cell hash that tiles across the longitude seam: the cell's
// x id wraps every px cells, so u = 0 and u = 1 sample identical cells
float cellHash(vec2 cellId, float px) {
    return hash21(vec2(mod(cellId.x, px), cellId.y));
}

// value noise on a wrapping lattice (quintic fade): 'per' tiles the
// field so it is seamless across the u = 0/1 longitude wrap
float vnoise(vec2 p, vec2 per) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float a = hash21(mod(i, per));
    float b = hash21(mod(i + vec2(1.0, 0.0), per));
    float cc = hash21(mod(i + vec2(0.0, 1.0), per));
    float d = hash21(mod(i + vec2(1.0, 1.0), per));
    return mix(mix(a, b, u.x), mix(cc, d, u.x), u.y);
}

// 3D value noise (quintic fade). Sampled on the sphere direction the
// domain is periodic across the u seam AND uniform at the poles by
// construction, so unlike the 2D lattice it needs NO wrap period.
float vnoise3(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    vec3 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float n000 = hash31(i);
    float n100 = hash31(i + vec3(1.0, 0.0, 0.0));
    float n010 = hash31(i + vec3(0.0, 1.0, 0.0));
    float n110 = hash31(i + vec3(1.0, 1.0, 0.0));
    float n001 = hash31(i + vec3(0.0, 0.0, 1.0));
    float n101 = hash31(i + vec3(1.0, 0.0, 1.0));
    float n011 = hash31(i + vec3(0.0, 1.0, 1.0));
    float n111 = hash31(i + vec3(1.0, 1.0, 1.0));
    return mix(mix(mix(n000, n100, u.x), mix(n010, n110, u.x), u.y),
        mix(mix(n001, n101, u.x), mix(n011, n111, u.x), u.y), u.z);
}

// 3D fractal noise, ridged mode, 4 octaves (budget: <= 4 --
// each octave costs 8 hashes). No wrap bookkeeping: the sphere-
// direction domain is seam- and pole-free by construction.
float fbm3(vec3 p) {
    float value = 0.0;
    float amplitude = 0.5;
    for (int i = 0; i < 4; i++) {
        value += amplitude * (1.0 - abs(2.0 * vnoise3(p) - 1.0));
        p = p * 2.0 + vec3(11.7, 5.3, 7.1);
        amplitude *= 0.5;
    }
    return value;
}

// divergence-free curl of a wrapping value-noise potential
vec2 curl2(vec2 p, vec2 per) {
    float e = 0.02;
    float n1 = vnoise(p + vec2(e, 0.0), per);
    float n2 = vnoise(p - vec2(e, 0.0), per);
    float n3 = vnoise(p + vec2(0.0, e), per);
    float n4 = vnoise(p - vec2(0.0, e), per);
    return vec2(n3 - n4, -(n1 - n2)) / (2.0 * e);
}

// iq cosine palette, baked per effect; used ONLY for bounded accents
vec3 accentPalette(float t) {
    return vec3(0.5) + vec3(0.5) * cos(6.2831853 * (vec3(0.7379, 0.8686, 1.2901) * t
        + vec3(0.3228, 0.7320, 0.8990)));
}

// 3-stop shadow/body/highlight grade (two smoothstep segments): every
// stop is derived from vertexColor.rgb at RUNTIME, so the owner /color
// override recolors shadow, body and highlight together (recolor-safe
// by construction).
vec3 gradient3(vec3 deepStop, vec3 body, vec3 hotStop, float x) {
    vec3 g = mix(deepStop, body, smoothstep(0.0, 0.5787, x));
    return mix(g, hotStop, smoothstep(0.5787, 1.0, x));
}

// saturation lift: mixes AWAY from luma (s > 1), deepening the chroma
// without changing the hue -- the anti-washout pass
vec3 satLift(vec3 col, float s) {
    float l = dot(col, vec3(0.299, 0.587, 0.114));
    return clamp(mix(vec3(l), col, s), 0.0, 1.0);
}

// Rodrigues rotation of the color vector around the grey axis; nudges
// the highlight stop's hue away from the body color. The input is
// always derived from vertexColor.rgb at runtime, so recolor-safe.
vec3 hueSpin(vec3 col, float a) {
    const vec3 k = vec3(0.57735027);
    float ca = cos(a);
    float sa = sin(a);
    return col * ca + cross(k, col) * sa + k * dot(k, col) * (1.0 - ca);
}

// latitude band rim: pole caps plus a soft equator belt
float rimLat(vec2 uv) {
    float lat = abs(uv.y * 2.0 - 1.0);
    float poles = smoothstep(0.7300, 1.0, lat);
    float belt = invsmooth(0.0, 0.2679, lat);
    return clamp(poles + 0.2552 * belt, 0.0, 1.0);
}

// GameTime-phased expanding rings from hash-seeded surface points; the
// chordal x-distance (sin of the longitude difference) keeps the rings
// round across the u = 0/1 seam, and the phase speed is day-quantized
float ringPulse(vec2 uv, float t) {
    float acc = 0.0;
    for (int i = 0; i < 3; i++) {
        float fi = float(i);
        vec2 c = hash22(vec2(fi * 7.31 + 5.5790, fi * 2.97));
        float phase = fract(t * 0.102500 + fi * 0.37);
        float d = length(vec2(sin((uv.x - c.x) * 3.1415927) * 0.3183, uv.y - c.y));
        acc += invsmooth(0.0, 0.05, abs(d - phase * 0.7)) * (1.0 - phase);
    }
    return acc;
}

// one inset-clamped tap of this file's surface-atlas tile: fract()
// wraps the (seam-periodic) repeat domain, and the inset keeps the
// linear-filtered lookup inside the tile for ANY flow/gradient offset
// (8x4 tile grid -> per-axis scale vec2(0.125, 0.25))
vec4 atlasTile(vec2 p) {
    return texture(Sampler0, (vec2(0.0000, 3.0000) + clamp(fract(p), 0.004, 0.996)) * vec2(0.125, 0.25));
}

// DEEP-layer field (3D fbm volume), sampled on the 3D sphere direction by
// the correlated parallax planes -- seam- and pole-free
float deepField(vec3 p, float t) {
    return fbm3(p);
}

void main() {
    // GameTime spans one day cycle in [0, 1); scale to roughly seconds.
    // All constant speeds below are day-quantized (integer cycles or
    // integer lattice periods per day) so the daily wrap does not pop.
    float time = GameTime * 1200.0;
    // texCoord0 is the raw sphere UV, already in [0,1]; fract() is only a
    // defensive wrap. Seam-freedom in u comes from the wrapping-lattice /
    // periodic-domain sampling below, NOT from this fract().
    vec2 baseUV = fract(texCoord0);
    vec2 midPer = vec2(8.0000, 10.0000);
    // 3D sphere direction reconstructed from the UV (u -> longitude,
    // v -> latitude): any field sampled on it is periodic across the
    // u = 0/1 seam AND uniform at the poles by construction.
    vec3 sdir = vec3(sin(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        cos(3.1415927 * baseUV.y),
        sin(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    // v11: the view direction is hoisted up here (the thickness and
    // parallax layers need it before the normal block) together with
    // its component TANGENT to the shell surface: Vt is the true
    // parallax direction -- zero head-on, maximal at the grazing limb,
    // seam-safe by construction (pure 3D geometry, no UV involved).
    vec3 viewV = -normalize(worldPos);
    vec3 Vt = viewV - dot(viewV, sdir) * sdir;

    // [palette:gradient3]
    // Runtime 3-stop palette derived from vertexColor.rgb: the dark stop
    // darkens AND saturates (base*base stays in-hue instead of greying);
    // the hot stop is a LUMA-CAPPED CHROMATIC highlight -- a hue-nudged,
    // saturation-lifted, brightened base whose luma is capped relative to
    // the base luma, so the highlight can NEVER wash out toward white.
    // The owner /color override replaces vertexColor wholesale, so the
    // whole ramp re-derives from it -- recolor-safe by construction.
    vec3 baseCol = vertexColor.rgb;
    vec3 deepStop = baseCol * baseCol * 0.6035;
    vec3 spun = clamp(hueSpin(baseCol, 0.5721), 0.0, 1.0);
    vec3 hotStop = satLift(spun, 1.1860) * 1.45;
    float hotLuma = dot(hotStop, vec3(0.299, 0.587, 0.114));
    float lumaCap = max(0.4950, dot(baseCol, vec3(0.299, 0.587, 0.114)) * 1.6691);
    hotStop = clamp(hotStop * min(1.0, lumaCap / max(hotLuma, 0.001)), 0.0, 1.0);
    // Secondary palette color, derived IN-SHADER from vertexColor via the
    // baked primary->secondary relation (hue angle + sat/value ratios) --
    // the vertex format has no second color attribute, and deriving both
    // from the live vertexColor keeps the owner recolor authoritative.
    vec3 secCol = clamp(satLift(clamp(hueSpin(baseCol, -2.6000), 0.0, 1.0), 0.7910) * 0.7480, 0.0, 1.0);

    // [layer:deep:parallax3d_fbm_x3]
    // Interior volume: correlated parallax PLANES of ONE deep field on
    // the 3D sphere direction, composited FRONT-TO-BACK under Beer-
    // Lambert transmittance -- each plane occludes the ones behind it,
    // and its light lands in BOTH the color accumulator (per-plane color
    // receding baseCol -> secCol -> dark stop) and the opacity term that
    // feeds the alpha. Farther planes show finer features, spin slower
    // (integer turns/day: the daily wrap lands on a full turn) and slide
    // along the TRUE view-tangent parallax direction (v11: par = Vt *
    // parScale replaces the old screen-space rimDir estimate -- planes
    // hold still head-on and shear apart toward the grazing limb).
    // (this family's mid layer still reads the screen-space slope)
    vec2 rimDirRaw = vec2(dFdx(sphericalVertexDistance), dFdy(sphericalVertexDistance));
    vec2 rimDir = rimDirRaw / (length(rimDirRaw) + 0.0001);
    vec3 spinAxis = vec3(-0.2169, 0.0398, -0.9754);
    vec3 par = Vt * 1.6282;
    // v11 breathing: the deep domain slowly in/exhales (day-quantized,
    // well under 2 Hz) so the interior volume reads alive, not baked.
    float deepBreath = 1.0 + 0.0119 * sin(time * 1.471313);
    float deepTrans = 1.0;
    vec3 deepCol = vec3(0.0);
    float dp = deepField(rotA(spinAxis, time * 0.083776) * (sdir * (2.9660 * deepBreath)), time);
    deepCol += deepTrans * dp * baseCol;
    deepTrans *= 1.0 - 0.5966 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.078540) * (sdir * (3.9379 * deepBreath)) + par * 0.0549, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 0.5335), deepStop, 0.1956);
    deepTrans *= 1.0 - 0.5966 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.073304) * (sdir * (4.9098 * deepBreath)) + par * 0.1097, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 1.0000), deepStop, 0.3912);
    deepTrans *= 1.0 - 0.5966 * clamp(dp, 0.0, 1.0);
    deepCol *= 1.0436;
    float deepPat = pow(clamp((1.0 - deepTrans) * 1.0702, 0.0, 1.0), 1.6039);

    // [layer:mid:holoparallax_curl_flicker]
    // Signature structure of this effect, domain-warped and animated.
    // v10 flicker: a smooth phase WANDER (two summed quantized sines,
    // each <= ~2 Hz) replaces the old hash11(floor(time * 2..5))
    // domain jump -- the nervous jitter stays visible but the pattern
    // domain moves CONTINUOUSLY, so it can never strobe
    // (photosensitivity), and the atlas can ride the same domain.
    float ft = time + 0.4544 * (0.6 * sin(time * 4.607669) + 0.4 * sin(time * 11.011282 + 1.7559));
    vec2 auv = vec2(baseUV.x * 8.0000, baseUV.y * 8.0000) + vec2(-0.213333, -0.208333) * ft;
    vec2 wuv = auv + 0.2385 * curl2(auv + vec2(0.0, time * 0.066667), midPer);
    // [layer:v5:polefade]
    // v5 pole guard: at v = 0/1 EVERY u maps to the same sphere point,
    // so this family's longitude-dependent 2D signature would pinch
    // into an apex starburst. The composer fades the signature (and any
    // longitude-dependent post color mix) toward a longitude-independent
    // body level near the poles; the 3D deep volume underneath is
    // pole-safe by construction, so the caps still read as material.
    float poleFade = smoothstep(0.015, 0.1404, min(baseUV.y, 1.0 - baseUV.y));
    float hpAcc = 0.0;
    for (int i = 0; i < 3; i++) {
        float fi = float(i);
        // integer per-layer scale keeps the grid seam-aligned; the
        // rimDir shift is the hologram's depth parallax
        vec2 hpUV = wuv * (fi + 1.0) + rimDir * (fi * 0.1009);
        vec2 hpD = abs(fract(hpUV) - 0.5);
        float hpGrid = smoothstep(0.4259, 0.4741, max(hpD.x, hpD.y));
        float hpScan = 0.5 + 0.5 * sin(hpUV.y * 13.7171 + time * 0.979130 - fi * 1.7);
        hpAcc += (hpGrid * 0.5500 + hpScan * 0.0798) * (1.0 - fi * 0.1825);
    }
    float hpSync = invsmooth(0.0, 0.0454, abs(baseUV.y - fract(time * 0.091667)));
    float hpFlick = 0.92 + 0.08 * sin(time * 7.817330);
    // pole guard on the grid layers only; the sync band is latitude-only
    // (pole-safe) and keeps sweeping across the caps
    float mid = clamp(mix(0.3000, hpAcc * hpFlick, poleFade) + hpSync * 0.4937, 0.0, 1.25);

    // [layer:tex:glyph_ring]
    // Real sampled detail from atlas tile 24 (glyph_ring), matched to this
    // family's technique. The INTEGER repeat multiplier keeps the lookup exact
    // across the u = 0/1 wrap (the domain spans an integer lattice period per
    // wrap, and its drifts shift integer periods per day -- day-wrap-safe);
    // the inset clamp keeps the linear-filtered sample inside this tile.
    // v9 family texture-drift: a baked per-FAMILY drift vector (direction
    // golden-angle-spread by family index, speed day-quantized against the
    // tile period) -- two families sharing a tile move it differently.
    vec2 texUV = wuv * 2.0000 + vec2(-0.028333, 0.012500) * time;
    // v8 height taps: the atlas R/G/B structural mix doubles as a HEIGHT
    // field. Its 2-tap gradient (a) tilts the shading normal (bump) and
    // (b) builds the divergence-free flow vector the energy crawls along.
    vec3 hgtW = vec3(0.4006, 0.3377, 0.2617);
    float hgtC = dot(atlasTile(texUV).rgb, hgtW);
    float hgtX = dot(atlasTile(texUV + vec2(0.0131, 0.0)).rgb, hgtW);
    float hgtY = dot(atlasTile(texUV + vec2(0.0, 0.0131)).rgb, hgtW);
    vec2 atlasSlope = vec2(hgtX - hgtC, hgtY - hgtC);
    // [layer:flow:atlas_curl]
    // v8 dual-phase flow-map advection: two taps advected along the curl
    // of the height field at half-cycle-offset fract phases, crossfaded
    // by phase distance -- the energy visibly CRAWLS across the membrane.
    // The phase speed completes integer cycles per day (day-wrap-safe)
    // and the flow vector is a function of the seam-periodic texUV domain
    // (u = 0/1 safe by construction).
    vec2 flowVec = vec2(atlasSlope.y, -atlasSlope.x) * -5.0775;
    float flowA = fract(time * 0.082500);
    float flowB = fract(flowA + 0.5);
    vec4 atlas = mix(atlasTile(texUV + flowVec * flowA), atlasTile(texUV + flowVec * flowB), abs(flowA - 0.5) * 2.0);
    // v7 atlas pole fade: texUV is longitude-dependent, so at v = 0/1 the
    // tile would pinch into an apex rosette. Every atlas INFLUENCE (mid
    // lift, body grade, emission) fades to its no-atlas value at the caps.
    float atlasPoleW = smoothstep(0.02, 0.12, min(baseUV.y, 1.0 - baseUV.y));
    float texDetail = clamp(atlas.r * 0.5488 + atlas.g * 0.4626 + atlas.b * 0.3585, 0.0, 1.0);
    // the multi-scale texture layers modulate the signature and add a lift
    // that is mostly GATED through the family's own pattern (v7) -- the
    // signature stays dominant and dark palettes keep their dark gaps
    mid = clamp(mid * mix(1.0, 0.7184 + 0.5630 * texDetail, atlasPoleW) + 0.1752 * texDetail * (0.3260 + 0.6740 * clamp(mid, 0.0, 1.0)) * atlasPoleW, 0.0, 1.5);

    // [layer:normal:atlas_bump]
    // v8 perturbed shading normal: the atlas height gradient tilts the
    // analytic sphere normal along its tangent frame (dsdir/du, dsdir/dv).
    // Pole-faded: the u tangent degenerates at the caps, so the bump
    // scales with atlasPoleW and the normal falls back to sdir there.
    vec3 tanU = vec3(-sin(6.2831853 * baseUV.x), 0.0, cos(6.2831853 * baseUV.x));
    vec3 tanV = vec3(cos(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        -sin(3.1415927 * baseUV.y),
        cos(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    vec3 bumpN = normalize(sdir + (tanU * atlasSlope.x + tanV * atlasSlope.y) * (1.3374 * atlasPoleW));
    // fresnel rim (view angle against the bumped normal; viewV was
    // hoisted next to sdir in v11): the classic force-field edge glow;
    // abs() keeps the back faces consistent
    float fresnel = pow(1.0 - abs(dot(bumpN, viewV)), 3.3612);

    // [layer:thick:paratex]
    // v11 in-shell texture parallax: two EXTRA atlas taps stepped along
    // the view tangent projected onto the tangent frame (VtUV) sample
    // the tile as if suspended deeper INSIDE the glass -- the detail
    // visibly shifts against the surface as the view moves. Seam/day-
    // safe: the offset lives on the periodic texUV domain.
    vec2 VtUV = vec2(dot(Vt, tanU), dot(Vt, tanV));
    vec3 deepTexA = atlasTile(texUV + VtUV * 0.0790).rgb;
    vec3 deepTexB = atlasTile(texUV - VtUV * 0.0790).rgb;
    float deepTex = 0.5 * (dot(deepTexA, hgtW) + dot(deepTexB, hgtW));

    // [layer:thick:chord]
    // v11 volumetric thickness: the membrane is a shell of relative
    // thickness rho = 0.0644 (geo material group) on the unit
    // sphere. chord = the view ray's path length through the shell,
    // normalized by the radial thickness and limb-clamped: chordN is
    // 1.0 head-on and saturates at 3.0 toward the grazing silhouette.
    // Two-case: while the ray still hits the inner sphere the path is
    // cosV - sqrt(disc); past the tangent ring it misses and runs the
    // full outer chord 2*cosV, capped at the inner-tangent maximum
    // 2*sqrt(1 - (1-rho)^2) = 0.7063.
    float cosV = abs(dot(sdir, viewV));
    float chordDisc = 0.9356 * 0.9356 - (1.0 - cosV * cosV);
    float chord = chordDisc > 0.0 ? cosV - sqrt(chordDisc) : min(2.0 * cosV, 0.7063);
    float chordN = min(chord / 0.0644, 3.0);

    // [layer:rim:lat]
    // Silhouette / band lift so the membrane reads as a curved shell:
    // a wide soft inner glow (style-specific) plus a thin hot line at
    // the very edge. The slope is normalized by the camera distance so
    // the rim width stays view-consistent near and far.
    float rimSlope = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    float rimLine = smoothstep(0.0588, 0.0930, rimSlope);
    float rim = rimLat(baseUV) * 0.9717;
    // v8: the fresnel term folds into the rim glow -- edges glow, the
    // center stays refraction-dominated (see the [layer:refract] mix).
    rim = clamp(rim + 0.6804 * rimLine + 0.5949 * fresnel, 0.0, 1.4);

    // Flourish accent + micro grain keep large areas alive up close.
    float flourish = 0.2723 * ringPulse(baseUV + vec2(0.13, 0.31), time);
    float grain = 0.0445 * (cellHash(floor(wuv * 29.0000) + vec2(floor(time * 2.0), 0.0), 232.0000) - 0.5);

    // [layer:motif:core:sparklegate]
    // v9 per-id motif fingerprint: this effect's unique moving bright
    // element (core x1) under its sparklegate emissive envelope.
    float motifEnv = 0.48 + 0.52 * smoothstep(0.30, 0.72, (0.5 + 0.5 * sin(time * 0.549779)) * (0.5 + 0.5 * sin(time * 0.717330 + 1.7)));
    vec2 motifC = vec2(sin((baseUV.x - 0.5) * 3.1415927) * 0.6366, baseUV.y - 0.5);
    float motifR = length(motifC);
    float motifM = exp(-motifR * motifR * 16.8512) * (0.75 + 0.25 * sin(time * 0.466003 + 4.8293));
    float motifGlow = clamp(motifM, 0.0, 1.2) * motifEnv;

    // Recolor-safe composite v4: the whole pattern is graded through the
    // vertexColor-derived 3-stop ramp (low pattern falls to the DARK stop
    // and low alpha -- never pale grey), the deep volume sits BEHIND the
    // signature structure, and the gradient position leans toward the hot
    // stop at the rim (chromatic rim). The vertexColor.a dissolve near
    // whitelisted players always wins the final alpha.
    // [layer:v5:slopeparallax]
    // v5 slope-parallax multi-tap: three EXTRA taps of the deep field,
    // stepped along the silhouette slope (par, screen-space: seam-safe)
    // at growing offset and scale -- the membrane texture itself gains
    // depth where the shell curves away from the view.
    float v5Par = deepField(sdir * 1.8586 + par * 0.0641, time) * 0.5;
    v5Par += deepField(sdir * 2.5092 + par * 0.1282, time) * 0.3;
    v5Par += deepField(sdir * 3.2526 + par * 0.1922, time) * 0.2;
    float pattern = clamp(0.2120 * deepPat * mix(1.0, chordN, 0.1701) + 0.9452 * mid + 0.6989 * rim + flourish + grain + 0.1982 * v5Par + 0.1785 * deepTex, 0.0, 1.5);
    float gpos = clamp(pattern * 0.8866 + rim * 0.1389, 0.0, 1.0);
    vec3 rgb = gradient3(deepStop, baseCol, hotStop, gpos);
    float midCover = clamp(1.0531 * mid + 0.4653 * rim, 0.0, 1.0);
    rgb = mix(deepCol, rgb, midCover);
    // [layer:tex:body] -- the sampled multi-scale detail also grades the
    // composited body (deep volume included). v7: the grade is pole-faded
    // and partly gated through the pattern, so the family signature stays
    // dominant over the tile texture and the caps keep their clean body.
    float texBody = 0.8272 + 0.4224 * texDetail;
    rgb *= mix(1.0, texBody, atlasPoleW * (0.5284 + 0.4716 * clamp(pattern, 0.0, 1.0)));
    rgb = satLift(rgb, 1.2377);
    // Hue-preserving soft-clip on the hot crests: brightness saturates
    // toward the palette's own bright tint (1 - exp(-k * hotStop * x)),
    // never toward additive white -- rich color instead of pastel.
    vec3 softHot = 1.0 - exp(-2.9986 * hotStop * (pattern + 0.35 * rim));
    rgb = mix(rgb, softHot, 0.2186 * smoothstep(0.55, 1.10, pattern));
    vec3 accent = accentPalette(0.0075 + pattern * 0.4076);
    rgb = mix(rgb, rgb * (0.55 + 0.9 * accent), 0.4225);
    // Two-band chromatic dispersion on the rim (thin-film-like), biased
    // to vertexColor.rgb: band 1 multiplies the wide glow into the
    // palette-driven rgb, band 2 pulls the thin hot line toward the (also
    // vertexColor-derived) hot stop. Both bounded -- the owner recolor
    // override stays authoritative on every rim style.
    vec3 rimDisp = 0.5 + 0.5 * cos(vec3(1.0, 0.8065, 0.6452) * (rim * 0.9147 + baseUV.y * 0.7892 + 0.3755) * 6.2831853);
    rgb = mix(rgb, rgb * (0.72 + 0.56 * rimDisp), clamp(rim, 0.0, 1.0) * 0.1018);
    vec3 lineDisp = 0.5 + 0.5 * cos(vec3(0.6452, 0.8065, 1.0) * (rimLine * 0.8033 + baseUV.y * 0.31 + 0.7628) * 6.2831853);
    rgb = mix(rgb, hotStop * (0.62 + 0.50 * lineDisp), clamp(rimLine, 0.0, 1.0) * 0.1852);
    // [layer:wash:high_luma]
    // v10 near-white wash guard: near-white/high-luma palettes (chrome,
    // crystal) still washed to white at the apex under the linear per-luma
    // guards, so a smoothstep factor cuts the specular add, the emissive
    // add/white-mix and the energy overlay much harder for bright palettes
    // ONLY, and darkens the low-pattern body so structure shows. Recolor-
    // safe: washHi derives from the live vertexColor luma, nothing baked.
    float baseLuma = dot(baseCol, vec3(0.299, 0.587, 0.114));
    float washHi = smoothstep(0.55, 0.85, baseLuma);
    // uniform pre-clip compression + extra darkening of the low-pattern
    // body: near-white crests otherwise all clip to 1.0 and flatten into
    // one white sheet at the apex.
    rgb *= (1.0 - 0.2702 * washHi) * (1.0 - 0.2556 * washHi * (1.0 - clamp(pattern, 0.0, 1.0)));
    // [layer:light:wrapkey]
    // v8 fake lighting: wrap-diffuse + specular from a FIXED world key
    // light against the bumped normal, applied to the ENERGY only (the
    // refracted scene below is already lit). Recolor-safe: the diffuse is
    // a bounded multiplicative grade and the specular adds the palette's
    // own luma-capped hot stop -- no baked hue anywhere.
    vec3 keyL = vec3(-0.5706, 0.6273, 0.5300);
    float keyDiff = clamp((dot(bumpN, keyL) + 0.5151) / 1.5151, 0.0, 1.0);
    rgb *= 0.6737 + 0.6059 * keyDiff * (1.0 - 0.5937 * washHi);
    float keySpec = pow(clamp(dot(reflect(-viewV, bumpN), keyL), 0.0, 1.0), 25.9278);
    rgb += hotStop * (keySpec * 0.4542 * (1.0 - 0.6782 * washHi));
    // [layer:glass:beer]
    // W6/1.21.1 glass composite: no scene copy on this target, so the
    // real world shows through the TRANSLUCENT blend (see the glass
    // alpha floor below) instead of a refracted scene sample. What
    // survives from the 26.2 refraction layer is the Beer-Lambert
    // chord absorption -- the glass base color is the live palette
    // absorbed along the view path through the shell, so grazing
    // paths tint deeper and stay in-hue (recolor-safe) -- and the
    // energy weight, which still balances the family's pattern
    // against the see-through glass base: gaps read as tinted glass
    // over the alpha-blended world, features as energy, edges glow.
    vec3 glassCol = baseCol * exp(-0.3810 * chordN * (1.0 - baseCol));
    glassCol *= mix(vec3(1.0), baseCol, 0.2004);
    float energyW = clamp(0.2528 + 0.4714 * clamp(pattern, 0.0, 1.0) + 0.2176 * fresnel, 0.0, 0.8380);
    // v10 wash guard on the overlay: white palettes show MORE glass
    // (and world) instead of piling white energy on white glass.
    energyW *= 1.0 - 0.2589 * washHi;
    rgb = mix(glassCol, rgb, energyW);
    rgb += fresnel * hotStop * (0.9469 * (1.0 - 0.6082 * washHi));
    // v9 motif add: the per-id moving bright element rides ON TOP of the
    // energy-glass composite so the fingerprint stays identifiable.
    // Recolor-safe: its color is a hotStop/secCol mix, both live-derived
    // from vertexColor; its envelope is <= 2 Hz and day-quantized.
    rgb += motifGlow * mix(hotStop, secCol, 0.1735) * 0.9570;
    // [layer:emit:atlas_a]
    // Emissive glow: atlas.a is an EMISSION mask (never transparency) --
    // filament cores / cell edges / cracks / sparkles ADD a bright, hue-
    // preserving tint of the live palette. v7 wash guard: both the white-
    // mix and the emissive gain fall off with the palette's own luma, so
    // bright palettes (chrome/pastel) glow IN HUE instead of blowing to
    // white, while dark palettes keep their full glow. Scaled by the
    // family's own highlights and a slow day-quantized breath -- the glow
    // is spatial and strobe-free by construction.
    // (baseLuma/washHi were computed in the v10 wash-guard layer above;
    // washHi additionally cuts the white-mix AND the emissive add for
    // near-white palettes -- they glow in hue, never toward white.)
    vec3 emitCol = clamp(mix(baseCol, vec3(1.0), 0.3119 * max(0.0, 1.0 - 0.4501 * baseLuma - 0.6774 * washHi)), 0.0, 1.0);
    float emit = atlas.a * (0.3057 + 0.6748 * clamp(pattern, 0.0, 1.0)) * (1.0 - 0.1533 * (0.5 + 0.5 * sin(time * 0.246091))) * atlasPoleW;
    rgb += emit * 0.8830 * (1.0 - 0.6525 * baseLuma) * (1.0 - 0.5116 * washHi) * emitCol;
    // [layer:v5:softknee]
    // v5 soft-knee highlight rolloff: channels over the knee compress
    // exponentially instead of clipping (continuous at the knee since
    // exp(0) = 1), so hot crests keep hue separation right up to white.
    vec3 v5Over = max(rgb - vec3(0.7481), vec3(0.0));
    rgb = min(rgb, vec3(0.7481)) + 0.2519 * (1.0 - exp(-v5Over * 2.0160));
    // [layer:wash:knee]
    // v10 washHi-gated soft-knee: for near-white palettes every additive
    // path (fresnel glow, motif, emission, specular) lands >= 1.0 and CLIPS,
    // flattening the apex into one white sheet -- compress the overshoot
    // exponentially instead so crest/gap structure survives up to white.
    // Identity for dark palettes (washHi = 0 -> knee = 1.0).
    float washKnee = 1.0 - 0.2175 * washHi;
    vec3 washOver = max(rgb - vec3(washKnee), vec3(0.0));
    rgb = min(rgb, vec3(washKnee)) + (1.0 - washKnee) * (1.0 - exp(-washOver * 3.2878));
    // Presence BODY alpha (family-tuned, v6 solidity lift): a firm membrane
    // base even between features, a solid floor wherever the pattern is
    // present, rising toward the ceiling on bright features, plus the deep
    // volume's Beer-Lambert opacity and the emissive glow. v7 dissolve
    // authority: EVERY alpha modifier (emission, back-face densify, ghost
    // thinning, dither) acts on this body value, which is clamped to the
    // family ceiling and only THEN multiplied by vertexColor.a -- the
    // whitelisted-player dissolve is always the final, outermost factor.
    float presence = smoothstep(0.02, 0.30, pattern);
    float bodyAlpha = 0.3571 + 0.2474 * presence + 0.4939 * pattern + 0.0817 * (1.0 - deepTrans) + 0.1506 * emit;
    // v9: the motif also firms the membrane locally (pre-clamp, pre-
    // dissolve -- vertexColor.a still always wins).
    bodyAlpha += motifGlow * 0.2310;
    // [layer:v5:backface]
    // v5 densify/dim (gl_FrontFacing is a builtin, no uniform needed).
    // Historical note: with the mesh's inward winding this condition is
    // TRUE on the CONVEX (near) face, not the far shell -- but every v5
    // family was tuned against exactly this look, so it stays on purpose
    // (the [layer:inner:*] block is the one keyed to the real far shell).
    float v5Back = gl_FrontFacing ? 0.0 : 1.0;
    rgb = mix(rgb, deepStop, v5Back * 0.3092);
    bodyAlpha *= 1.0 + v5Back * 0.2694;
    // [layer:v5:ghostalpha]
    // v5 luminance-weighted ghost translucency: dark areas thin out while
    // bright features hold. Multiplicative on the body alpha (pre-clamp,
    // pre-dissolve), so the vertexColor.a dissolve still always wins.
    float v5Luma = dot(clamp(rgb, 0.0, 1.0), vec3(0.299, 0.587, 0.114));
    bodyAlpha *= 0.7714 + 0.2286 * smoothstep(0.03, 0.42, v5Luma);
    // [layer:v5:dither]
    // v5 blue-noise-style alpha dither (interleaved gradient noise on
    // gl_FragCoord) breaks translucency banding; multiplicative on the
    // body alpha, so bodyAlpha = 0 stays exactly 0 and the ceiling clamp
    // below still bounds it.
    float v5Dither = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));
    bodyAlpha *= 1.0 + (v5Dither - 0.5) * 0.1184;
    // [layer:inner:scaffold]
    // v11 far-shell interior: with the mesh's inward winding and cull OFF,
    // gl_FrontFacing is TRUE exactly where the camera sees the concave side
    // (the far shell from outside, the whole wall from inside).
    float innerFace = gl_FrontFacing ? 1.0 : 0.0;
    // INNER_SCAFFOLD: the R (coarse structure) channel of the two
    // slope-parallax paratex taps builds the interior lattice (the
    // taps already shift with the view: structural parallax for free).
    float innerScaf = clamp(0.5 * (deepTexA.r + deepTexB.r) * 1.0301 + hgtC * 0.3103, 0.0, 1.0);
    // geo/tech group: a 2x-coarser GHOST of this id's motif is etched
    // into the scaffold (the pow widens the Gaussian/band footprint
    // to roughly twice the surface motif's size)
    innerScaf = clamp(innerScaf + 0.2869 * pow(clamp(motifM, 0.0, 1.0), 0.25), 0.0, 1.0);
    vec3 innerCol = mix(deepStop, secCol, innerScaf);
    rgb = mix(rgb, innerCol, innerFace * 0.3191);
    bodyAlpha *= 1.0 + innerFace * 0.1491;
    // [layer:alpha:glassfloor]
    // W6/1.21.1 glass alpha floor, folded into bodyAlpha BEFORE the
    // ceiling clamp: the 26.2 near-opaque refraction floor becomes a
    // TRANSLUCENT floor -- the world behind the membrane is revealed by
    // the alpha blend now, so the gaps must stay genuinely see-through.
    // (No depth-soft fade either: that needed the scene depth copy.)
    bodyAlpha = max(bodyAlpha, 0.3486);
    // dissolve authority: clamp the body to the family ceiling FIRST, then
    // apply the whitelisted-player dissolve as the LAST alpha operation --
    // no path can push the final alpha above vertexColor.a * ceiling.
    float alpha = clamp(bodyAlpha, 0.0, 0.8731) * vertexColor.a;
    vec4 color = vec4(clamp(rgb, 0.0, 1.0), alpha);
    if (color.a < 0.01) {
        discard;
    }
    // vanilla 1.21.1 fog: linear_fog over the FogShape-picked distance
    // metric, exactly like the vanilla core shaders' fog_distance(pos,
    // FogShape) split across the two precomputed varyings.
    fragColor = linear_fog(color, FogShape == 0 ? sphericalVertexDistance : cylindricalVertexDistance, FogStart, FogEnd, FogColor);
}
