#version 150

#moj_import <fog.glsl>

// The shipped surface atlas (bubbleshield:textures/effect/surface_atlas.png,
// bound by ShieldPipelines' per-effect RenderType through its
// TextureStateShard): an 8x4 grid of 32 seamless grayscale tiles. Per texel:
// R = coarse structure, G = mid detail, B = fine grain, A = EMISSION mask
// (glow, NOT transparency). All hue comes from vertexColor at runtime
// (recolor-safe).
uniform sampler2D Sampler0;
// Vanilla auto-filled uniforms (declared in fx_NNN.json; ShaderInstance
// .setDefaultUniforms fills them every draw). GameTime spans one day cycle
// in [0, 1); FogShape picks the vanilla fog metric (0 = spherical).
uniform float GameTime;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;
uniform int FogShape;

// Bubble surface shader fx_632 -- family MYCELIA
// stack: deep=caustic x3 taps | mid=mycelia+curl+rotate | rim=lat | flourish=swirl | tex=lightning_web | motif=orbitx3+heartbeat
// fbm: standard x6 octaves | seed 2d24a817d21cc8a5
// v12 realism (1.21.1): glass tint 0.5323+Beer 0.6165*chord | energy 0.4334+0.3978*p | flow 0.070000 c/s | floor 0.3410
// GENERATED by tools/gen_surface_shaders.py -- do not hand-edit; edit the
// generator and regenerate instead (byte-stable, fixed seed).

in vec2 texCoord0;
in vec4 vertexColor;
in float sphericalVertexDistance;
in float cylindricalVertexDistance;
// Camera-relative world-space position from surface.vsh: the camera is
// the origin of this space, so view direction = -normalize(worldPos).
in vec3 worldPos;

out vec4 fragColor;

// 1 - smoothstep with ASCENDING edges. Replaces every reversed-edge
// smoothstep(hi, lo, x) call: edge0 >= edge1 is undefined by the GLSL
// spec; this form is numerically identical on conforming drivers.
float invsmooth(float lo, float hi, float x) {
    return 1.0 - smoothstep(lo, hi, x);
}

// Rodrigues rotation matrix around a baked unit axis. Driven with an
// angle that completes an INTEGER number of turns per day, the daily
// time wrap 1200 -> 0 lands exactly on a full turn -- the catalogue's
// first true (non-shear) rotation animation, only legal on the 3D
// sphere-direction domain (a 2D UV rotation would break the u wrap).
mat3 rotA(vec3 axis, float a) {
    float s = sin(a);
    float c = cos(a);
    float oc = 1.0 - c;
    return mat3(
        oc * axis.x * axis.x + c, oc * axis.x * axis.y + axis.z * s, oc * axis.z * axis.x - axis.y * s,
        oc * axis.x * axis.y - axis.z * s, oc * axis.y * axis.y + c, oc * axis.y * axis.z + axis.x * s,
        oc * axis.z * axis.x + axis.y * s, oc * axis.y * axis.z - axis.x * s, oc * axis.z * axis.z + c);
}

float hash21(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

// Hoskins-style 3D->1D hash; small multiplier keeps fp32 precision
// alive over the whole sphere-direction domain
float hash31(vec3 p3) {
    p3 = fract(p3 * 0.1031);
    p3 += dot(p3, p3.zyx + 31.32);
    return fract((p3.x + p3.y) * p3.z);
}

// lattice-cell hash that tiles across the longitude seam: the cell's
// x id wraps every px cells, so u = 0 and u = 1 sample identical cells
float cellHash(vec2 cellId, float px) {
    return hash21(vec2(mod(cellId.x, px), cellId.y));
}

// value noise on a wrapping lattice (quintic fade): 'per' tiles the
// field so it is seamless across the u = 0/1 longitude wrap
float vnoise(vec2 p, vec2 per) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float a = hash21(mod(i, per));
    float b = hash21(mod(i + vec2(1.0, 0.0), per));
    float cc = hash21(mod(i + vec2(0.0, 1.0), per));
    float d = hash21(mod(i + vec2(1.0, 1.0), per));
    return mix(mix(a, b, u.x), mix(cc, d, u.x), u.y);
}

// 3D value noise (quintic fade). Sampled on the sphere direction the
// domain is periodic across the u seam AND uniform at the poles by
// construction, so unlike the 2D lattice it needs NO wrap period.
float vnoise3(vec3 p) {
    vec3 i = floor(p);
    vec3 f = fract(p);
    vec3 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    float n000 = hash31(i);
    float n100 = hash31(i + vec3(1.0, 0.0, 0.0));
    float n010 = hash31(i + vec3(0.0, 1.0, 0.0));
    float n110 = hash31(i + vec3(1.0, 1.0, 0.0));
    float n001 = hash31(i + vec3(0.0, 0.0, 1.0));
    float n101 = hash31(i + vec3(1.0, 0.0, 1.0));
    float n011 = hash31(i + vec3(0.0, 1.0, 1.0));
    float n111 = hash31(i + vec3(1.0, 1.0, 1.0));
    return mix(mix(mix(n000, n100, u.x), mix(n010, n110, u.x), u.y),
        mix(mix(n001, n101, u.x), mix(n011, n111, u.x), u.y), u.z);
}

// fractal noise, standard mode, 6 octaves. The x lacunarity
// is exactly 2 and the lattice period doubles with it, so EVERY octave
// tiles the longitude seam (a rotation here would break the wrap).
float fbm2(vec2 p, vec2 per) {
    float value = 0.0;
    float amplitude = 0.5;
    for (int i = 0; i < 6; i++) {
        value += amplitude * vnoise(p, per);
        p = vec2(p.x * 2.0, p.y * 2.1953) + vec2(17.7, 9.2);
        per = vec2(per.x * 2.0, per.y * 2.1953);
        amplitude *= 0.5;
    }
    return value;
}

// divergence-free curl of a wrapping value-noise potential
vec2 curl2(vec2 p, vec2 per) {
    float e = 0.02;
    float n1 = vnoise(p + vec2(e, 0.0), per);
    float n2 = vnoise(p - vec2(e, 0.0), per);
    float n3 = vnoise(p + vec2(0.0, e), per);
    float n4 = vnoise(p - vec2(0.0, e), per);
    return vec2(n3 - n4, -(n1 - n2)) / (2.0 * e);
}

// iterated caustic on the 3D sphere direction: noise-displaced
// resampling + exp sharpen, seam- and pole-free by construction.
// Motion comes from the caller rotating the domain (day-safe).
float caustic3(vec3 p, float t) {
    vec3 k = p;
    float acc = 0.0;
    for (int i = 0; i < 3; i++) {
        float fi = float(i);
        float w = vnoise3(k + vec3(fi * 3.7, fi * 1.3, fi * 2.1));
        k += 0.35 * vec3(cos(w * 6.2831853), sin(w * 6.2831853), cos(w * 4.1887902 + 1.7));
        acc += w;
    }
    acc = acc / 3.0;
    return clamp(exp(acc * 3.0 - 1.9) - 0.35, 0.0, 1.4);
}

// iq cosine palette, baked per effect; used ONLY for bounded accents
vec3 accentPalette(float t) {
    return vec3(0.5) + vec3(0.5) * cos(6.2831853 * (vec3(1.0439, 0.9121, 0.8865) * t
        + vec3(0.4547, 0.3180, 0.7175)));
}

// 3-stop shadow/body/highlight grade (two smoothstep segments): every
// stop is derived from vertexColor.rgb at RUNTIME, so the owner /color
// override recolors shadow, body and highlight together (recolor-safe
// by construction).
vec3 gradient3(vec3 deepStop, vec3 body, vec3 hotStop, float x) {
    vec3 g = mix(deepStop, body, smoothstep(0.0, 0.5663, x));
    return mix(g, hotStop, smoothstep(0.5663, 1.0, x));
}

// saturation lift: mixes AWAY from luma (s > 1), deepening the chroma
// without changing the hue -- the anti-washout pass
vec3 satLift(vec3 col, float s) {
    float l = dot(col, vec3(0.299, 0.587, 0.114));
    return clamp(mix(vec3(l), col, s), 0.0, 1.0);
}

// Rodrigues rotation of the color vector around the grey axis; nudges
// the highlight stop's hue away from the body color. The input is
// always derived from vertexColor.rgb at runtime, so recolor-safe.
vec3 hueSpin(vec3 col, float a) {
    const vec3 k = vec3(0.57735027);
    float ca = cos(a);
    float sa = sin(a);
    return col * ca + cross(k, col) * sa + k * dot(k, col) * (1.0 - ca);
}

// latitude band rim: pole caps plus a soft equator belt
float rimLat(vec2 uv) {
    float lat = abs(uv.y * 2.0 - 1.0);
    float poles = smoothstep(0.5835, 1.0, lat);
    float belt = invsmooth(0.0, 0.3138, lat);
    return clamp(poles + 0.3353 * belt, 0.0, 1.0);
}

// distance from p to the line segment a-b (classic iq segment SDF);
// used by the branch/filament/glyph v5 families
float sdSeg(vec2 p, vec2 a, vec2 b) {
    vec2 pa = p - a;
    vec2 ba = b - a;
    float h = clamp(dot(pa, ba) / max(dot(ba, ba), 1e-6), 0.0, 1.0);
    return length(pa - ba * h);
}

// one inset-clamped tap of this file's surface-atlas tile: fract()
// wraps the (seam-periodic) repeat domain, and the inset keeps the
// linear-filtered lookup inside the tile for ANY flow/gradient offset
// (8x4 tile grid -> per-axis scale vec2(0.125, 0.25))
vec4 atlasTile(vec2 p) {
    return texture(Sampler0, (vec2(0.0000, 2.0000) + clamp(fract(p), 0.004, 0.996)) * vec2(0.125, 0.25));
}

// DEEP-layer field (3D refracted caustic volume), sampled on the 3D sphere direction by
// the correlated parallax planes -- seam- and pole-free
float deepField(vec3 p, float t) {
    return caustic3(p, t);
}

void main() {
    // GameTime spans one day cycle in [0, 1); scale to roughly seconds.
    // All constant speeds below are day-quantized (integer cycles or
    // integer lattice periods per day) so the daily wrap does not pop.
    float time = GameTime * 1200.0;
    // texCoord0 is the raw sphere UV, already in [0,1]; fract() is only a
    // defensive wrap. Seam-freedom in u comes from the wrapping-lattice /
    // periodic-domain sampling below, NOT from this fract().
    vec2 baseUV = fract(texCoord0);
    vec2 midPer = vec2(10.0000, 12.0000);
    // 3D sphere direction reconstructed from the UV (u -> longitude,
    // v -> latitude): any field sampled on it is periodic across the
    // u = 0/1 seam AND uniform at the poles by construction.
    vec3 sdir = vec3(sin(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        cos(3.1415927 * baseUV.y),
        sin(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    // v11: the view direction is hoisted up here (the thickness and
    // parallax layers need it before the normal block) together with
    // its component TANGENT to the shell surface: Vt is the true
    // parallax direction -- zero head-on, maximal at the grazing limb,
    // seam-safe by construction (pure 3D geometry, no UV involved).
    vec3 viewV = -normalize(worldPos);
    vec3 Vt = viewV - dot(viewV, sdir) * sdir;

    // [palette:gradient3]
    // Runtime 3-stop palette derived from vertexColor.rgb: the dark stop
    // darkens AND saturates (base*base stays in-hue instead of greying);
    // the hot stop is a LUMA-CAPPED CHROMATIC highlight -- a hue-nudged,
    // saturation-lifted, brightened base whose luma is capped relative to
    // the base luma, so the highlight can NEVER wash out toward white.
    // The owner /color override replaces vertexColor wholesale, so the
    // whole ramp re-derives from it -- recolor-safe by construction.
    vec3 baseCol = vertexColor.rgb;
    vec3 deepStop = baseCol * baseCol * 0.5962;
    vec3 spun = clamp(hueSpin(baseCol, -0.1801), 0.0, 1.0);
    vec3 hotStop = satLift(spun, 1.1640) * 1.45;
    float hotLuma = dot(hotStop, vec3(0.299, 0.587, 0.114));
    float lumaCap = max(0.5761, dot(baseCol, vec3(0.299, 0.587, 0.114)) * 1.6055);
    hotStop = clamp(hotStop * min(1.0, lumaCap / max(hotLuma, 0.001)), 0.0, 1.0);
    // Secondary palette color, derived IN-SHADER from vertexColor via the
    // baked primary->secondary relation (hue angle + sat/value ratios) --
    // the vertex format has no second color attribute, and deriving both
    // from the live vertexColor keeps the owner recolor authoritative.
    vec3 secCol = clamp(satLift(clamp(hueSpin(baseCol, 0.4188), 0.0, 1.0), 1.1084) * 0.4185, 0.0, 1.0);

    // [layer:deep:parallax3d_caustic_x3]
    // Interior volume: correlated parallax PLANES of ONE deep field on
    // the 3D sphere direction, composited FRONT-TO-BACK under Beer-
    // Lambert transmittance -- each plane occludes the ones behind it,
    // and its light lands in BOTH the color accumulator (per-plane color
    // receding baseCol -> secCol -> dark stop) and the opacity term that
    // feeds the alpha. Farther planes show finer features, spin slower
    // (integer turns/day: the daily wrap lands on a full turn) and slide
    // along the TRUE view-tangent parallax direction (v11: par = Vt *
    // parScale replaces the old screen-space rimDir estimate -- planes
    // hold still head-on and shear apart toward the grazing limb).
    vec3 spinAxis = vec3(-0.7435, -0.3316, 0.5807);
    vec3 par = Vt * 1.7673;
    // v11 breathing: the deep domain slowly in/exhales (day-quantized,
    // well under 2 Hz) so the interior volume reads alive, not baked.
    float deepBreath = 1.0 + 0.0129 * sin(time * 0.989602);
    float deepTrans = 1.0;
    vec3 deepCol = vec3(0.0);
    float dp = deepField(rotA(spinAxis, time * 0.041888) * (sdir * (2.7637 * deepBreath)), time);
    deepCol += deepTrans * dp * baseCol;
    deepTrans *= 1.0 - 0.5524 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.036652) * (sdir * (4.2016 * deepBreath)) + par * 0.0314, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 0.5506), deepStop, 0.2019);
    deepTrans *= 1.0 - 0.5524 * clamp(dp, 0.0, 1.0);
    dp = deepField(rotA(spinAxis, time * 0.031416) * (sdir * (5.6396 * deepBreath)) + par * 0.0628, time);
    deepCol += deepTrans * dp * mix(mix(baseCol, secCol, 1.0000), deepStop, 0.4038);
    deepTrans *= 1.0 - 0.5524 * clamp(dp, 0.0, 1.0);
    deepCol *= 0.8116;
    float deepPat = pow(clamp((1.0 - deepTrans) * 1.0985, 0.0, 1.0), 1.4085);

    // [layer:mid:mycelia_curl_rotate]
    // Signature structure of this effect, domain-warped and animated.
    // seam-safe stand-in for domain rotation: true rotation would mix
    // latitude into longitude and break the u wrap, so the pattern
    // leans (shears) back and forth instead.
    float sway = 1.2758 * sin(time * 0.225147);
    vec2 auv = vec2(baseUV.x * 10.0000 + (baseUV.y - 0.5) * sway + time * -0.141667, baseUV.y * 10.0000);
    vec2 wuv = auv + 0.2515 * curl2(auv + vec2(0.0, time * 0.070000), midPer);
    // [layer:v5:polefade]
    // v5 pole guard: at v = 0/1 EVERY u maps to the same sphere point,
    // so this family's longitude-dependent 2D signature would pinch
    // into an apex starburst. The composer fades the signature (and any
    // longitude-dependent post color mix) toward a longitude-independent
    // body level near the poles; the 3D deep volume underneath is
    // pole-safe by construction, so the caps still read as material.
    float poleFade = smoothstep(0.015, 0.1197, min(baseUV.y, 1.0 - baseUV.y));
    vec2 myI = floor(wuv);
    vec2 myF = fract(wuv);
    vec2 myN0 = vec2(cellHash(myI, midPer.x), cellHash(myI + 71.3, midPer.x)) * 0.6 + 0.2;
    float myD = 8.0;
    float myPh = 0.0;
    for (int k = 0; k < 4; k++) {
        vec2 og = (k == 0) ? vec2(1.0, 0.0) : ((k == 1) ? vec2(-1.0, 0.0) : ((k == 2) ? vec2(0.0, 1.0) : vec2(0.0, -1.0)));
        vec2 nc = myI + og;
        vec2 nn = og + vec2(cellHash(nc, midPer.x), cellHash(nc + 71.3, midPer.x)) * 0.6 + 0.2;
        float sd = sdSeg(myF, myN0, nn);
        if (sd < myD) { myD = sd; myPh = cellHash(nc + 13.9, midPer.x); }
    }
    float myFil = invsmooth(0.0240, 0.0727, myD);
    float myGlow = invsmooth(0.05, 0.3261, myD);
    float myNode = invsmooth(0.02, 0.07, length(myF - myN0));
    // traveling growth pulse: a wavefront sweeps the network by phase
    float myPulse = pow(0.5 + 0.5 * sin(time * 0.958186 - (myI.y + myPh * 4.9803) * 0.8671), 4.6364);
    float mid = clamp(myFil * (0.5878 + 0.5795 * myPulse) + myNode * 0.5 * myPulse + myGlow * 0.15 * myPulse, 0.0, 1.2);
    // pole guard: the thread lattice pinches at the apexes; fade toward
    // the network's sparse body level
    mid = mix(0.1000, mid, poleFade);

    // [layer:tex:lightning_web]
    // Real sampled detail from atlas tile 16 (lightning_web), matched to this
    // family's technique. The INTEGER repeat multiplier keeps the lookup exact
    // across the u = 0/1 wrap (the domain spans an integer lattice period per
    // wrap, and its drifts shift integer periods per day -- day-wrap-safe);
    // the inset clamp keeps the linear-filtered sample inside this tile.
    // v9 family texture-drift: a baked per-FAMILY drift vector (direction
    // golden-angle-spread by family index, speed day-quantized against the
    // tile period) -- two families sharing a tile move it differently.
    vec2 texUV = wuv * 1.0000 + vec2(0.021667, -0.035833) * time;
    // v8 height taps: the atlas R/G/B structural mix doubles as a HEIGHT
    // field. Its 2-tap gradient (a) tilts the shading normal (bump) and
    // (b) builds the divergence-free flow vector the energy crawls along.
    vec3 hgtW = vec3(0.4890, 0.2935, 0.2175);
    float hgtC = dot(atlasTile(texUV).rgb, hgtW);
    float hgtX = dot(atlasTile(texUV + vec2(0.0146, 0.0)).rgb, hgtW);
    float hgtY = dot(atlasTile(texUV + vec2(0.0, 0.0146)).rgb, hgtW);
    vec2 atlasSlope = vec2(hgtX - hgtC, hgtY - hgtC);
    // [layer:flow:atlas_curl]
    // v8 dual-phase flow-map advection: two taps advected along the curl
    // of the height field at half-cycle-offset fract phases, crossfaded
    // by phase distance -- the energy visibly CRAWLS across the membrane.
    // The phase speed completes integer cycles per day (day-wrap-safe)
    // and the flow vector is a function of the seam-periodic texUV domain
    // (u = 0/1 safe by construction).
    vec2 flowVec = vec2(atlasSlope.y, -atlasSlope.x) * 2.5682;
    float flowA = fract(time * 0.070000);
    float flowB = fract(flowA + 0.5);
    vec4 atlas = mix(atlasTile(texUV + flowVec * flowA), atlasTile(texUV + flowVec * flowB), abs(flowA - 0.5) * 2.0);
    // v7 atlas pole fade: texUV is longitude-dependent, so at v = 0/1 the
    // tile would pinch into an apex rosette. Every atlas INFLUENCE (mid
    // lift, body grade, emission) fades to its no-atlas value at the caps.
    float atlasPoleW = smoothstep(0.02, 0.12, min(baseUV.y, 1.0 - baseUV.y));
    float texDetail = clamp(atlas.r * 0.5299 + atlas.g * 0.3180 + atlas.b * 0.2357, 0.0, 1.0);
    // the multi-scale texture layers modulate the signature and add a lift
    // that is mostly GATED through the family's own pattern (v7) -- the
    // signature stays dominant and dark palettes keep their dark gaps
    mid = clamp(mid * mix(1.0, 0.6811 + 0.5498 * texDetail, atlasPoleW) + 0.1234 * texDetail * (0.2506 + 0.7494 * clamp(mid, 0.0, 1.0)) * atlasPoleW, 0.0, 1.5);

    // [layer:normal:atlas_bump]
    // v8 perturbed shading normal: the atlas height gradient tilts the
    // analytic sphere normal along its tangent frame (dsdir/du, dsdir/dv).
    // Pole-faded: the u tangent degenerates at the caps, so the bump
    // scales with atlasPoleW and the normal falls back to sdir there.
    vec3 tanU = vec3(-sin(6.2831853 * baseUV.x), 0.0, cos(6.2831853 * baseUV.x));
    vec3 tanV = vec3(cos(3.1415927 * baseUV.y) * cos(6.2831853 * baseUV.x),
        -sin(3.1415927 * baseUV.y),
        cos(3.1415927 * baseUV.y) * sin(6.2831853 * baseUV.x));
    vec3 bumpN = normalize(sdir + (tanU * atlasSlope.x + tanV * atlasSlope.y) * (1.0530 * atlasPoleW));
    // fresnel rim (view angle against the bumped normal; viewV was
    // hoisted next to sdir in v11): the classic force-field edge glow;
    // abs() keeps the back faces consistent
    float fresnel = pow(1.0 - abs(dot(bumpN, viewV)), 3.4809);

    // [layer:thick:paratex]
    // v11 in-shell texture parallax: two EXTRA atlas taps stepped along
    // the view tangent projected onto the tangent frame (VtUV) sample
    // the tile as if suspended deeper INSIDE the glass -- the detail
    // visibly shifts against the surface as the view moves. Seam/day-
    // safe: the offset lives on the periodic texUV domain.
    vec2 VtUV = vec2(dot(Vt, tanU), dot(Vt, tanV));
    vec3 deepTexA = atlasTile(texUV + VtUV * 0.0654).rgb;
    vec3 deepTexB = atlasTile(texUV - VtUV * 0.0654).rgb;
    float deepTex = 0.5 * (dot(deepTexA, hgtW) + dot(deepTexB, hgtW));

    // [layer:thick:chord]
    // v11 volumetric thickness: the membrane is a shell of relative
    // thickness rho = 0.1401 (organic material group) on the unit
    // sphere. chord = the view ray's path length through the shell,
    // normalized by the radial thickness and limb-clamped: chordN is
    // 1.0 head-on and saturates at 3.0 toward the grazing silhouette.
    // Two-case: while the ray still hits the inner sphere the path is
    // cosV - sqrt(disc); past the tangent ring it misses and runs the
    // full outer chord 2*cosV, capped at the inner-tangent maximum
    // 2*sqrt(1 - (1-rho)^2) = 1.0208.
    float cosV = abs(dot(sdir, viewV));
    float chordDisc = 0.8599 * 0.8599 - (1.0 - cosV * cosV);
    float chord = chordDisc > 0.0 ? cosV - sqrt(chordDisc) : min(2.0 * cosV, 1.0208);
    float chordN = min(chord / 0.1401, 3.0);

    // [layer:rim:lat]
    // Silhouette / band lift so the membrane reads as a curved shell:
    // a wide soft inner glow (style-specific) plus a thin hot line at
    // the very edge. The slope is normalized by the camera distance so
    // the rim width stays view-consistent near and far.
    float rimSlope = fwidth(sphericalVertexDistance) / max(sphericalVertexDistance, 1.0);
    float rimLine = smoothstep(0.0749, 0.1000, rimSlope);
    float rim = rimLat(baseUV) * 0.6571;
    // v8: the fresnel term folds into the rim glow -- edges glow, the
    // center stays refraction-dominated (see the [layer:refract] mix).
    rim = clamp(rim + 0.6203 * rimLine + 0.8465 * fresnel, 0.0, 1.4);

    // Flourish accent + micro grain keep large areas alive up close.
    float flourish = 0.1981 * pow(clamp(fbm2(wuv + vec2(-time * 0.083333, time * 0.070000), midPer), 0.0, 1.0), 2.0);
    float grain = 0.0561 * (cellHash(floor(wuv * 55.0000) + vec2(floor(time * 2.0), 0.0), 550.0000) - 0.5);

    // [layer:motif:orbit:heartbeat]
    // v9 per-id motif fingerprint: this effect's unique moving bright
    // element (orbit x3) under its heartbeat emissive envelope.
    float motifP = fract(time * 0.464167 + 0.7719);
    float motifEnv = 0.50 + 0.80 * pow(max(sin(motifP * 6.2831853), 0.0), 6.0) + 0.52 * pow(max(sin((motifP - 0.14) * 6.2831853), 0.0), 10.0);
    float motifM = 0.0;
    float motifO0 = fract(0.6666 + -1.0 * time * 0.025000);
    float motifL0 = 0.4621 + 0.1231 * sin(time * 0.324631 + 0.0000);
    vec2 motifD0 = vec2(sin((baseUV.x - motifO0) * 3.1415927) * 0.6366, baseUV.y - motifL0);
    motifM += exp(-dot(motifD0, motifD0) * 69.6325);
    float motifO1 = fract(0.9999 + -1.0 * time * 0.025000);
    float motifL1 = 0.4621 + 0.1231 * sin(time * 0.324631 + 2.4000);
    vec2 motifD1 = vec2(sin((baseUV.x - motifO1) * 3.1415927) * 0.6366, baseUV.y - motifL1);
    motifM += exp(-dot(motifD1, motifD1) * 69.6325);
    float motifO2 = fract(1.3333 + -1.0 * time * 0.025000);
    float motifL2 = 0.4621 + 0.1231 * sin(time * 0.324631 + 4.8000);
    vec2 motifD2 = vec2(sin((baseUV.x - motifO2) * 3.1415927) * 0.6366, baseUV.y - motifL2);
    motifM += exp(-dot(motifD2, motifD2) * 69.6325);
    float motifGlow = clamp(motifM, 0.0, 1.2) * motifEnv;

    // Recolor-safe composite v4: the whole pattern is graded through the
    // vertexColor-derived 3-stop ramp (low pattern falls to the DARK stop
    // and low alpha -- never pale grey), the deep volume sits BEHIND the
    // signature structure, and the gradient position leans toward the hot
    // stop at the rim (chromatic rim). The vertexColor.a dissolve near
    // whitelisted players always wins the final alpha.
    // [layer:v5:slopeparallax]
    // v5 slope-parallax multi-tap: three EXTRA taps of the deep field,
    // stepped along the silhouette slope (par, screen-space: seam-safe)
    // at growing offset and scale -- the membrane texture itself gains
    // depth where the shell curves away from the view.
    float v5Par = deepField(sdir * 1.7514 + par * 0.0589, time) * 0.5;
    v5Par += deepField(sdir * 2.3644 + par * 0.1178, time) * 0.3;
    v5Par += deepField(sdir * 3.0649 + par * 0.1767, time) * 0.2;
    float pattern = clamp(0.2689 * deepPat * mix(1.0, chordN, 0.2023) + 0.7139 * mid + 0.8092 * rim + flourish + grain + 0.2116 * v5Par + 0.2120 * deepTex, 0.0, 1.5);
    float gpos = clamp(pattern * 0.9417 + rim * 0.2235, 0.0, 1.0);
    vec3 rgb = gradient3(deepStop, baseCol, hotStop, gpos);
    float midCover = clamp(0.8652 * mid + 0.4403 * rim, 0.0, 1.0);
    rgb = mix(deepCol, rgb, midCover);
    // [layer:tex:body] -- the sampled multi-scale detail also grades the
    // composited body (deep volume included). v7: the grade is pole-faded
    // and partly gated through the pattern, so the family signature stays
    // dominant over the tile texture and the caps keep their clean body.
    float texBody = 0.8568 + 0.3500 * texDetail;
    rgb *= mix(1.0, texBody, atlasPoleW * (0.5182 + 0.4818 * clamp(pattern, 0.0, 1.0)));
    rgb = satLift(rgb, 1.2119);
    // Hue-preserving soft-clip on the hot crests: brightness saturates
    // toward the palette's own bright tint (1 - exp(-k * hotStop * x)),
    // never toward additive white -- rich color instead of pastel.
    vec3 softHot = 1.0 - exp(-2.8700 * hotStop * (pattern + 0.35 * rim));
    rgb = mix(rgb, softHot, 0.2429 * smoothstep(0.55, 1.10, pattern));
    vec3 accent = accentPalette(0.7080 + pattern * 0.3353);
    rgb = mix(rgb, rgb * (0.55 + 0.9 * accent), 0.1874);
    // Two-band chromatic dispersion on the rim (thin-film-like), biased
    // to vertexColor.rgb: band 1 multiplies the wide glow into the
    // palette-driven rgb, band 2 pulls the thin hot line toward the (also
    // vertexColor-derived) hot stop. Both bounded -- the owner recolor
    // override stays authoritative on every rim style.
    vec3 rimDisp = 0.5 + 0.5 * cos(vec3(1.0, 0.8065, 0.6452) * (rim * 1.0793 + baseUV.y * 0.4704 + 0.8871) * 6.2831853);
    rgb = mix(rgb, rgb * (0.72 + 0.56 * rimDisp), clamp(rim, 0.0, 1.0) * 0.1799);
    vec3 lineDisp = 0.5 + 0.5 * cos(vec3(0.6452, 0.8065, 1.0) * (rimLine * 0.9147 + baseUV.y * 0.31 + 0.4967) * 6.2831853);
    rgb = mix(rgb, hotStop * (0.62 + 0.50 * lineDisp), clamp(rimLine, 0.0, 1.0) * 0.2698);
    // [layer:wash:high_luma]
    // v10 near-white wash guard: near-white/high-luma palettes (chrome,
    // crystal) still washed to white at the apex under the linear per-luma
    // guards, so a smoothstep factor cuts the specular add, the emissive
    // add/white-mix and the energy overlay much harder for bright palettes
    // ONLY, and darkens the low-pattern body so structure shows. Recolor-
    // safe: washHi derives from the live vertexColor luma, nothing baked.
    float baseLuma = dot(baseCol, vec3(0.299, 0.587, 0.114));
    float washHi = smoothstep(0.55, 0.85, baseLuma);
    // uniform pre-clip compression + extra darkening of the low-pattern
    // body: near-white crests otherwise all clip to 1.0 and flatten into
    // one white sheet at the apex.
    rgb *= (1.0 - 0.2948 * washHi) * (1.0 - 0.4000 * washHi * (1.0 - clamp(pattern, 0.0, 1.0)));
    // [layer:light:wrapkey]
    // v8 fake lighting: wrap-diffuse + specular from a FIXED world key
    // light against the bumped normal, applied to the ENERGY only (the
    // refracted scene below is already lit). Recolor-safe: the diffuse is
    // a bounded multiplicative grade and the specular adds the palette's
    // own luma-capped hot stop -- no baked hue anywhere.
    vec3 keyL = vec3(0.2778, 0.9606, -0.0061);
    float keyDiff = clamp((dot(bumpN, keyL) + 0.4212) / 1.4212, 0.0, 1.0);
    rgb *= 0.6207 + 0.4651 * keyDiff * (1.0 - 0.4681 * washHi);
    float keySpec = pow(clamp(dot(reflect(-viewV, bumpN), keyL), 0.0, 1.0), 15.8419);
    rgb += hotStop * (keySpec * 0.2563 * (1.0 - 0.6532 * washHi));
    // [layer:glass:beer]
    // W6/1.21.1 glass composite: no scene copy on this target, so the
    // real world shows through the TRANSLUCENT blend (see the glass
    // alpha floor below) instead of a refracted scene sample. What
    // survives from the 26.2 refraction layer is the Beer-Lambert
    // chord absorption -- the glass base color is the live palette
    // absorbed along the view path through the shell, so grazing
    // paths tint deeper and stay in-hue (recolor-safe) -- and the
    // energy weight, which still balances the family's pattern
    // against the see-through glass base: gaps read as tinted glass
    // over the alpha-blended world, features as energy, edges glow.
    vec3 glassCol = baseCol * exp(-0.6165 * chordN * (1.0 - baseCol));
    glassCol *= mix(vec3(1.0), baseCol, 0.5323);
    float energyW = clamp(0.4334 + 0.3978 * clamp(pattern, 0.0, 1.0) + 0.2333 * fresnel, 0.0, 0.8149);
    // v10 wash guard on the overlay: white palettes show MORE glass
    // (and world) instead of piling white energy on white glass.
    energyW *= 1.0 - 0.2539 * washHi;
    rgb = mix(glassCol, rgb, energyW);
    rgb += fresnel * hotStop * (0.9602 * (1.0 - 0.5544 * washHi));
    // v9 motif add: the per-id moving bright element rides ON TOP of the
    // energy-glass composite so the fingerprint stays identifiable.
    // Recolor-safe: its color is a hotStop/secCol mix, both live-derived
    // from vertexColor; its envelope is <= 2 Hz and day-quantized.
    rgb += motifGlow * mix(hotStop, secCol, 0.4415) * 0.9108;
    // [layer:emit:atlas_a]
    // Emissive glow: atlas.a is an EMISSION mask (never transparency) --
    // filament cores / cell edges / cracks / sparkles ADD a bright, hue-
    // preserving tint of the live palette. v7 wash guard: both the white-
    // mix and the emissive gain fall off with the palette's own luma, so
    // bright palettes (chrome/pastel) glow IN HUE instead of blowing to
    // white, while dark palettes keep their full glow. Scaled by the
    // family's own highlights and a slow day-quantized breath -- the glow
    // is spatial and strobe-free by construction.
    // (baseLuma/washHi were computed in the v10 wash-guard layer above;
    // washHi additionally cuts the white-mix AND the emissive add for
    // near-white palettes -- they glow in hue, never toward white.)
    vec3 emitCol = clamp(mix(baseCol, vec3(1.0), 0.3174 * max(0.0, 1.0 - 0.5701 * baseLuma - 0.6084 * washHi)), 0.0, 1.0);
    float emit = atlas.a * (0.3065 + 0.6457 * clamp(pattern, 0.0, 1.0)) * (1.0 - 0.1633 * (0.5 + 0.5 * sin(time * 0.172788))) * atlasPoleW;
    rgb += emit * 0.8869 * (1.0 - 0.7363 * baseLuma) * (1.0 - 0.4892 * washHi) * emitCol;
    // [layer:v5:softknee]
    // v5 soft-knee highlight rolloff: channels over the knee compress
    // exponentially instead of clipping (continuous at the knee since
    // exp(0) = 1), so hot crests keep hue separation right up to white.
    vec3 v5Over = max(rgb - vec3(0.7024), vec3(0.0));
    rgb = min(rgb, vec3(0.7024)) + 0.2976 * (1.0 - exp(-v5Over * 2.3097));
    // [layer:wash:knee]
    // v10 washHi-gated soft-knee: for near-white palettes every additive
    // path (fresnel glow, motif, emission, specular) lands >= 1.0 and CLIPS,
    // flattening the apex into one white sheet -- compress the overshoot
    // exponentially instead so crest/gap structure survives up to white.
    // Identity for dark palettes (washHi = 0 -> knee = 1.0).
    float washKnee = 1.0 - 0.2558 * washHi;
    vec3 washOver = max(rgb - vec3(washKnee), vec3(0.0));
    rgb = min(rgb, vec3(washKnee)) + (1.0 - washKnee) * (1.0 - exp(-washOver * 4.6514));
    // Presence BODY alpha (family-tuned, v6 solidity lift): a firm membrane
    // base even between features, a solid floor wherever the pattern is
    // present, rising toward the ceiling on bright features, plus the deep
    // volume's Beer-Lambert opacity and the emissive glow. v7 dissolve
    // authority: EVERY alpha modifier (emission, back-face densify, ghost
    // thinning, dither) acts on this body value, which is clamped to the
    // family ceiling and only THEN multiplied by vertexColor.a -- the
    // whitelisted-player dissolve is always the final, outermost factor.
    float presence = smoothstep(0.02, 0.30, pattern);
    float bodyAlpha = 0.3545 + 0.2689 * presence + 0.5172 * pattern + 0.1527 * (1.0 - deepTrans) + 0.1238 * emit;
    // v9: the motif also firms the membrane locally (pre-clamp, pre-
    // dissolve -- vertexColor.a still always wins).
    bodyAlpha += motifGlow * 0.2387;
    // [layer:v5:backface]
    // v5 densify/dim (gl_FrontFacing is a builtin, no uniform needed).
    // Historical note: with the mesh's inward winding this condition is
    // TRUE on the CONVEX (near) face, not the far shell -- but every v5
    // family was tuned against exactly this look, so it stays on purpose
    // (the [layer:inner:*] block is the one keyed to the real far shell).
    float v5Back = gl_FrontFacing ? 0.0 : 1.0;
    rgb = mix(rgb, deepStop, v5Back * 0.3159);
    bodyAlpha *= 1.0 + v5Back * 0.1703;
    // [layer:v5:ghostalpha]
    // v5 luminance-weighted ghost translucency: dark areas thin out while
    // bright features hold. Multiplicative on the body alpha (pre-clamp,
    // pre-dissolve), so the vertexColor.a dissolve still always wins.
    float v5Luma = dot(clamp(rgb, 0.0, 1.0), vec3(0.299, 0.587, 0.114));
    bodyAlpha *= 0.7389 + 0.2611 * smoothstep(0.03, 0.42, v5Luma);
    // [layer:v5:dither]
    // v5 blue-noise-style alpha dither (interleaved gradient noise on
    // gl_FragCoord) breaks translucency banding; multiplicative on the
    // body alpha, so bodyAlpha = 0 stays exactly 0 and the ceiling clamp
    // below still bounds it.
    float v5Dither = fract(52.9829189 * fract(dot(gl_FragCoord.xy, vec2(0.06711056, 0.00583715))));
    bodyAlpha *= 1.0 + (v5Dither - 0.5) * 0.0880;
    // [layer:inner:fogbank]
    // v11 far-shell interior: with the mesh's inward winding and cull OFF,
    // gl_FrontFacing is TRUE exactly where the camera sees the concave side
    // (the far shell from outside, the whole wall from inside).
    float innerFace = gl_FrontFacing ? 1.0 : 0.0;
    // INNER_FOGBANK: a slow fog bank fills the shell; denser fog
    // absorbs the interior light (Beer-consistent with the raised
    // group k) and recedes toward the dark stop with a 0.9 aerial-
    // perspective reach.
    float innerFog = clamp(deepField(rotA(spinAxis, time * 0.031416 + 5.9661) * (sdir * 2.4873), time) * 1.1225 + 0.2168, 0.0, 1.0);
    vec3 innerCol = mix(mix(baseCol, secCol, 0.55), deepStop, 0.9 * innerFog);
    rgb = mix(rgb, innerCol, innerFace * 0.1915);
    bodyAlpha *= 1.0 + innerFace * 0.1113;
    // [layer:alpha:glassfloor]
    // W6/1.21.1 glass alpha floor, folded into bodyAlpha BEFORE the
    // ceiling clamp: the 26.2 near-opaque refraction floor becomes a
    // TRANSLUCENT floor -- the world behind the membrane is revealed by
    // the alpha blend now, so the gaps must stay genuinely see-through.
    // (No depth-soft fade either: that needed the scene depth copy.)
    bodyAlpha = max(bodyAlpha, 0.3410);
    // dissolve authority: clamp the body to the family ceiling FIRST, then
    // apply the whitelisted-player dissolve as the LAST alpha operation --
    // no path can push the final alpha above vertexColor.a * ceiling.
    float alpha = clamp(bodyAlpha, 0.0, 0.8526) * vertexColor.a;
    vec4 color = vec4(clamp(rgb, 0.0, 1.0), alpha);
    if (color.a < 0.01) {
        discard;
    }
    // vanilla 1.21.1 fog: linear_fog over the FogShape-picked distance
    // metric, exactly like the vanilla core shaders' fog_distance(pos,
    // FogShape) split across the two precomputed varyings.
    fragColor = linear_fog(color, FogShape == 0 ? sphericalVertexDistance : cylindricalVertexDistance, FogStart, FogEnd, FogColor);
}
